/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IB20FactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createB20"
      | "getB20Address"
      | "isB20"
      | "isB20Initialized"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createB20",
    values: [BigNumberish, BytesLike, BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getB20Address",
    values: [BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "isB20", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "isB20Initialized",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "createB20", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getB20Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isB20", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isB20Initialized",
    data: BytesLike
  ): Result;
}

export interface IB20Factory extends BaseContract {
  connect(runner?: ContractRunner | null): IB20Factory;
  waitForDeployment(): Promise<this>;

  interface: IB20FactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createB20: TypedContractMethod<
    [
      variant: BigNumberish,
      salt: BytesLike,
      params: BytesLike,
      initCalls: BytesLike[]
    ],
    [string],
    "nonpayable"
  >;

  getB20Address: TypedContractMethod<
    [variant: BigNumberish, deployer: AddressLike, salt: BytesLike],
    [string],
    "view"
  >;

  isB20: TypedContractMethod<[addr: AddressLike], [boolean], "view">;

  isB20Initialized: TypedContractMethod<[addr: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createB20"
  ): TypedContractMethod<
    [
      variant: BigNumberish,
      salt: BytesLike,
      params: BytesLike,
      initCalls: BytesLike[]
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getB20Address"
  ): TypedContractMethod<
    [variant: BigNumberish, deployer: AddressLike, salt: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "isB20"
  ): TypedContractMethod<[addr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isB20Initialized"
  ): TypedContractMethod<[addr: AddressLike], [boolean], "view">;

  filters: {};
}
