/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IB20Factory } from "./IB20Factory";
export type { IB20Token } from "./IB20Token";
export type { IPolicyRegistry } from "./IPolicyRegistry";
