/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IPolicyRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createPolicy"
      | "createPolicyWithAccounts"
      | "finalizeUpdateAdmin"
      | "isAuthorized"
      | "policyAdmin"
      | "policyExists"
      | "renounceAdmin"
      | "stageUpdateAdmin"
      | "updateAllowlist"
      | "updateBlocklist"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createPolicy",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createPolicyWithAccounts",
    values: [AddressLike, BigNumberish, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeUpdateAdmin",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorized",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "policyAdmin",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "policyExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceAdmin",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stageUpdateAdmin",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAllowlist",
    values: [BigNumberish, boolean, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "updateBlocklist",
    values: [BigNumberish, boolean, AddressLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "createPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPolicyWithAccounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeUpdateAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "policyAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "policyExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stageUpdateAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAllowlist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateBlocklist",
    data: BytesLike
  ): Result;
}

export interface IPolicyRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IPolicyRegistry;
  waitForDeployment(): Promise<this>;

  interface: IPolicyRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createPolicy: TypedContractMethod<
    [admin: AddressLike, policyType: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  createPolicyWithAccounts: TypedContractMethod<
    [admin: AddressLike, policyType: BigNumberish, accounts: AddressLike[]],
    [bigint],
    "nonpayable"
  >;

  finalizeUpdateAdmin: TypedContractMethod<
    [policyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  isAuthorized: TypedContractMethod<
    [policyId: BigNumberish, account: AddressLike],
    [boolean],
    "view"
  >;

  policyAdmin: TypedContractMethod<[policyId: BigNumberish], [string], "view">;

  policyExists: TypedContractMethod<
    [policyId: BigNumberish],
    [boolean],
    "view"
  >;

  renounceAdmin: TypedContractMethod<
    [policyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  stageUpdateAdmin: TypedContractMethod<
    [policyId: BigNumberish, newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  updateAllowlist: TypedContractMethod<
    [policyId: BigNumberish, allow: boolean, accounts: AddressLike[]],
    [void],
    "nonpayable"
  >;

  updateBlocklist: TypedContractMethod<
    [policyId: BigNumberish, block: boolean, accounts: AddressLike[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createPolicy"
  ): TypedContractMethod<
    [admin: AddressLike, policyType: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createPolicyWithAccounts"
  ): TypedContractMethod<
    [admin: AddressLike, policyType: BigNumberish, accounts: AddressLike[]],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finalizeUpdateAdmin"
  ): TypedContractMethod<[policyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isAuthorized"
  ): TypedContractMethod<
    [policyId: BigNumberish, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "policyAdmin"
  ): TypedContractMethod<[policyId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "policyExists"
  ): TypedContractMethod<[policyId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceAdmin"
  ): TypedContractMethod<[policyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stageUpdateAdmin"
  ): TypedContractMethod<
    [policyId: BigNumberish, newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateAllowlist"
  ): TypedContractMethod<
    [policyId: BigNumberish, allow: boolean, accounts: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateBlocklist"
  ): TypedContractMethod<
    [policyId: BigNumberish, block: boolean, accounts: AddressLike[]],
    [void],
    "nonpayable"
  >;

  filters: {};
}
