/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockGroth16VerifierSol from "./MockGroth16Verifier.sol";
export type { mockGroth16VerifierSol };
import type * as mockUsdcSol from "./MockUSDC.sol";
export type { mockUsdcSol };
export type { MockCounter } from "./MockCounter";
