/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockUsdcSol from "./MockUSDC.sol";
export type { mockUsdcSol };
export type { MockCounter } from "./MockCounter";
export type { MockGroth16Verifier } from "./MockGroth16Verifier";
