/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ib20FactorySol from "./IB20Factory.sol";
export type { ib20FactorySol };
export type { IAuthorityModule } from "./IAuthorityModule";
export type { IEntryPoint } from "./IEntryPoint";
