/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PasskeyAuthority } from "./PasskeyAuthority";
export type { SessionKeyAuthority } from "./SessionKeyAuthority";
export type { WebAuthnPasskeyAuthority } from "./WebAuthnPasskeyAuthority";
