/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface SessionKeyAuthorityInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "KIND_POLIS_SSO"
      | "KIND_SESSION"
      | "isValidSignature"
      | "kind"
      | "kindOf"
      | "tier"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "KIND_POLIS_SSO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KIND_SESSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isValidSignature",
    values: [AddressLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "kind", values?: undefined): string;
  encodeFunctionData(functionFragment: "kindOf", values?: undefined): string;
  encodeFunctionData(functionFragment: "tier", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "KIND_POLIS_SSO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "KIND_SESSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "kind", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "kindOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tier", data: BytesLike): Result;
}

export interface SessionKeyAuthority extends BaseContract {
  connect(runner?: ContractRunner | null): SessionKeyAuthority;
  waitForDeployment(): Promise<this>;

  interface: SessionKeyAuthorityInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  KIND_POLIS_SSO: TypedContractMethod<[], [string], "view">;

  KIND_SESSION: TypedContractMethod<[], [string], "view">;

  isValidSignature: TypedContractMethod<
    [
      account: AddressLike,
      digest: BytesLike,
      config: BytesLike,
      signature: BytesLike
    ],
    [boolean],
    "view"
  >;

  kind: TypedContractMethod<[], [string], "view">;

  kindOf: TypedContractMethod<[], [string], "view">;

  tier: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "KIND_POLIS_SSO"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "KIND_SESSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isValidSignature"
  ): TypedContractMethod<
    [
      account: AddressLike,
      digest: BytesLike,
      config: BytesLike,
      signature: BytesLike
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "kind"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "kindOf"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tier"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
