/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface WebAuthnPasskeyAuthorityInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "KIND"
      | "isValidSignature"
      | "kind"
      | "requireUserVerification"
      | "tier"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "KIND", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isValidSignature",
    values: [AddressLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "kind", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "requireUserVerification",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "tier", values?: undefined): string;

  decodeFunctionResult(functionFragment: "KIND", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isValidSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "kind", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requireUserVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tier", data: BytesLike): Result;
}

export interface WebAuthnPasskeyAuthority extends BaseContract {
  connect(runner?: ContractRunner | null): WebAuthnPasskeyAuthority;
  waitForDeployment(): Promise<this>;

  interface: WebAuthnPasskeyAuthorityInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  KIND: TypedContractMethod<[], [string], "view">;

  isValidSignature: TypedContractMethod<
    [
      arg0: AddressLike,
      digest: BytesLike,
      config: BytesLike,
      signature: BytesLike
    ],
    [boolean],
    "view"
  >;

  kind: TypedContractMethod<[], [string], "view">;

  requireUserVerification: TypedContractMethod<[], [boolean], "view">;

  tier: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "KIND"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isValidSignature"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      digest: BytesLike,
      config: BytesLike,
      signature: BytesLike
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "kind"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "requireUserVerification"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "tier"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
