/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as company from "./company";
export type { company };
import type * as escrow from "./escrow";
export type { escrow };
import type * as treasury from "./treasury";
export type { treasury };
import type * as wallet from "./wallet";
export type { wallet };
