/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace CofferdamSubTreasuryFactory {
  export type SubTreasuryConfigStruct = {
    companyAnchor: BytesLike;
    spender: AddressLike;
    allowance: BigNumberish;
    periodSeconds: BigNumberish;
    role: BytesLike;
  };

  export type SubTreasuryConfigStructOutput = [
    companyAnchor: string,
    spender: string,
    allowance: bigint,
    periodSeconds: bigint,
    role: string
  ] & {
    companyAnchor: string;
    spender: string;
    allowance: bigint;
    periodSeconds: bigint;
    role: string;
  };
}

export interface CofferdamSubTreasuryFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "createSubTreasury" | "subTreasuries"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "SubTreasuryCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "createSubTreasury",
    values: [CofferdamSubTreasuryFactory.SubTreasuryConfigStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "subTreasuries",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createSubTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subTreasuries",
    data: BytesLike
  ): Result;
}

export namespace SubTreasuryCreatedEvent {
  export type InputTuple = [
    subTreasury: AddressLike,
    companyAnchor: BytesLike,
    spender: AddressLike,
    allowance: BigNumberish
  ];
  export type OutputTuple = [
    subTreasury: string,
    companyAnchor: string,
    spender: string,
    allowance: bigint
  ];
  export interface OutputObject {
    subTreasury: string;
    companyAnchor: string;
    spender: string;
    allowance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CofferdamSubTreasuryFactory extends BaseContract {
  connect(runner?: ContractRunner | null): CofferdamSubTreasuryFactory;
  waitForDeployment(): Promise<this>;

  interface: CofferdamSubTreasuryFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createSubTreasury: TypedContractMethod<
    [_config: CofferdamSubTreasuryFactory.SubTreasuryConfigStruct],
    [string],
    "nonpayable"
  >;

  subTreasuries: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, bigint, string] & {
        companyAnchor: string;
        spender: string;
        allowance: bigint;
        periodSeconds: bigint;
        role: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createSubTreasury"
  ): TypedContractMethod<
    [_config: CofferdamSubTreasuryFactory.SubTreasuryConfigStruct],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "subTreasuries"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, bigint, string] & {
        companyAnchor: string;
        spender: string;
        allowance: bigint;
        periodSeconds: bigint;
        role: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "SubTreasuryCreated"
  ): TypedContractEvent<
    SubTreasuryCreatedEvent.InputTuple,
    SubTreasuryCreatedEvent.OutputTuple,
    SubTreasuryCreatedEvent.OutputObject
  >;

  filters: {
    "SubTreasuryCreated(address,bytes32,address,uint256)": TypedContractEvent<
      SubTreasuryCreatedEvent.InputTuple,
      SubTreasuryCreatedEvent.OutputTuple,
      SubTreasuryCreatedEvent.OutputObject
    >;
    SubTreasuryCreated: TypedContractEvent<
      SubTreasuryCreatedEvent.InputTuple,
      SubTreasuryCreatedEvent.OutputTuple,
      SubTreasuryCreatedEvent.OutputObject
    >;
  };
}
