/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  CofferdamSubTreasuryFactory,
  CofferdamSubTreasuryFactoryInterface,
} from "../../../../contracts/enterprise/treasury/CofferdamSubTreasuryFactory";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "subTreasury",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "companyAnchor",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "address",
        name: "spender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "allowance",
        type: "uint256",
      },
    ],
    name: "SubTreasuryCreated",
    type: "event",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "companyAnchor",
            type: "bytes32",
          },
          {
            internalType: "address",
            name: "spender",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "allowance",
            type: "uint256",
          },
          {
            internalType: "uint32",
            name: "periodSeconds",
            type: "uint32",
          },
          {
            internalType: "bytes32",
            name: "role",
            type: "bytes32",
          },
        ],
        internalType: "struct CofferdamSubTreasuryFactory.SubTreasuryConfig",
        name: "_config",
        type: "tuple",
      },
    ],
    name: "createSubTreasury",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "subTreasuries",
    outputs: [
      {
        internalType: "bytes32",
        name: "companyAnchor",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "spender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "allowance",
        type: "uint256",
      },
      {
        internalType: "uint32",
        name: "periodSeconds",
        type: "uint32",
      },
      {
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080806040523460155761029d908161001a8239f35b5f80fdfe6080806040526004361015610012575f80fd5b5f3560e01c908163350489e7146100aa575063849d7d6014610032575f80fd5b346100a65760203660031901126100a6576004356001600160a01b038116908190036100a6575f525f60205260a060405f20805490600180841b03600182015416906002810154600463ffffffff600384015416920154926040519485526020850152604084015260608301526080820152f35b5f80fd5b346100a65760a03660031901126100a65760a0810181811067ffffffffffffffff8211176102535760405260043581526024356001600160a01b03811681036100a65760208201908152604082019160443583526064359063ffffffff821682036100a65760608101918252608435608082019081525f808052602081815292517fad3228b676f7d3cd4284a5443f17f1962b36e491b30a40b2405849e597ba5fb581905594517fad3228b676f7d3cd4284a5443f17f1962b36e491b30a40b2405849e597ba5fb680546001600160a01b0319166001600160a01b0392909216918217905595517fad3228b676f7d3cd4284a5443f17f1962b36e491b30a40b2405849e597ba5fb781905593517fad3228b676f7d3cd4284a5443f17f1962b36e491b30a40b2405849e597ba5fb8805463ffffffff191663ffffffff9290921691909117905590517fad3228b676f7d3cd4284a5443f17f1962b36e491b30a40b2405849e597ba5fb9556040805195865291850192909252919290917fbcba949b96b52a02c593d6b4554af4877a358b3042caf251d786a389de0d0abf91a360206040515f8152f35b634e487b7160e01b5f52604160045260245ffdfea2646970667358221220b87ccae8297df2f61e22c10d9810a1183f86d05492a5cc4dc327684a9b21e08a64736f6c634300081c0033";

type CofferdamSubTreasuryFactoryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CofferdamSubTreasuryFactoryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CofferdamSubTreasuryFactory__factory extends ContractFactory {
  constructor(...args: CofferdamSubTreasuryFactoryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      CofferdamSubTreasuryFactory & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): CofferdamSubTreasuryFactory__factory {
    return super.connect(runner) as CofferdamSubTreasuryFactory__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CofferdamSubTreasuryFactoryInterface {
    return new Interface(_abi) as CofferdamSubTreasuryFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): CofferdamSubTreasuryFactory {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as CofferdamSubTreasuryFactory;
  }
}
