/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  AuthorityManagerBase,
  AuthorityManagerBaseInterface,
} from "../../../contracts/account/AuthorityManagerBase";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "authorityId",
        type: "uint256",
      },
    ],
    name: "InactiveAuthority",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "authorityId",
        type: "uint256",
      },
    ],
    name: "InvalidAuthoritySignature",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "enum Tier",
        name: "tier",
        type: "uint8",
      },
    ],
    name: "NotAPasskey",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "enum Tier",
        name: "tier",
        type: "uint8",
      },
    ],
    name: "NotUntrustedLowTier",
    type: "error",
  },
  {
    inputs: [],
    name: "PasskeyAlreadyExists",
    type: "error",
  },
  {
    inputs: [],
    name: "PasskeyCapReached",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "enum Tier",
        name: "tier",
        type: "uint8",
      },
    ],
    name: "TierNotPermitted",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "authorityId",
        type: "uint256",
      },
    ],
    name: "UnknownAuthority",
    type: "error",
  },
  {
    inputs: [],
    name: "UpgradeLocked",
    type: "error",
  },
  {
    inputs: [],
    name: "ZeroModule",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "authorityId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "module",
        type: "address",
      },
      {
        indexed: false,
        internalType: "enum Tier",
        name: "tier",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "kind",
        type: "bytes32",
      },
    ],
    name: "AuthorityAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "authorityId",
        type: "uint256",
      },
    ],
    name: "AuthorityRevoked",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "lowAuthorityId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "passkeyAuthorityId",
        type: "uint256",
      },
    ],
    name: "FirstPasskeyEnrolled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [],
    name: "RatchetFired",
    type: "event",
  },
  {
    inputs: [],
    name: "MAX_PASSKEYS",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "authorityCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "authorityId",
        type: "uint256",
      },
    ],
    name: "getAuthority",
    outputs: [
      {
        internalType: "address",
        name: "module",
        type: "address",
      },
      {
        internalType: "enum Tier",
        name: "tier",
        type: "uint8",
      },
      {
        internalType: "bool",
        name: "active",
        type: "bool",
      },
      {
        internalType: "bytes",
        name: "config",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "passkeyCount",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "upgradeLocked",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class AuthorityManagerBase__factory {
  static readonly abi = _abi;
  static createInterface(): AuthorityManagerBaseInterface {
    return new Interface(_abi) as AuthorityManagerBaseInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AuthorityManagerBase {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as AuthorityManagerBase;
  }
}
