/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  CofferdamWalletBind,
  CofferdamWalletBindInterface,
} from "../../../../contracts/enterprise/wallet/CofferdamWalletBind";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "companyAnchor",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "workerWallet",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "ssoProofHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint48",
        name: "timestamp",
        type: "uint48",
      },
    ],
    name: "WalletBound",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "companyAnchor",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "workerWallet",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint48",
        name: "timestamp",
        type: "uint48",
      },
    ],
    name: "WalletUnbound",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_companyAnchor",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "_workerWallet",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "_ssoProofHash",
        type: "bytes32",
      },
    ],
    name: "bindWallet",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "bindings",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_companyAnchor",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "_workerWallet",
        type: "address",
      },
    ],
    name: "isBound",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "ssoProofs",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_companyAnchor",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "_workerWallet",
        type: "address",
      },
    ],
    name: "unbindWallet",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080806040523460155761030d908161001a8239f35b5f80fdfe60806040526004361015610011575f80fd5b5f3560e01c80633d7901c0146101c85780635d8e81a51461018457806362d5a25d1461009c57806398abeb33146100505763ced1771b14610050575f80fd5b34610098576040366003190112610098576100696102c1565b6004355f525f60205260405f209060018060a01b03165f52602052602060ff60405f2054166040519015158152f35b5f80fd5b34610098576040366003190112610098576004356100b86102c1565b90805f525f60205260405f2060018060a01b0383165f5260205260ff60405f20541615610153575f818152602081815260408083206001600160a01b0395909516808452948252808320805460ff191690558383526001825280832085845282528083209290925590514265ffffffffffff1681527fe96b1a518232dc842771cc7e411f115f0f4fc907cf01719836e475ae53bd85229190a3005b60405162461bcd60e51b8152602060048201526009602482015268139bdd08189bdd5b9960ba1b6044820152606490fd5b346100985760403660031901126100985761019d6102c1565b6004355f52600160205260405f209060018060a01b03165f52602052602060405f2054604051908152f35b34610098576060366003190112610098576004356101e46102c1565b9060443591815f525f60205260405f2060018060a01b0382165f5260205260ff60405f20541661028c575f828152602081815260408083206001600160a01b03909416808452938252808320805460ff19166001908117909155858452825280832084845282529182902085905581519485524265ffffffffffff169085015290927f436054a5a3a66a472931c492442bb63f4fbd4fab552e6656c4652d3d2b94375e9190a3005b60405162461bcd60e51b815260206004820152600d60248201526c105b1c9958591e48189bdd5b99609a1b6044820152606490fd5b602435906001600160a01b03821682036100985756fea2646970667358221220b89a710dbd4ffc44d2364be193aa71c0bb74976591f41628ff2196bed389e9ee64736f6c634300081c0033";

type CofferdamWalletBindConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CofferdamWalletBindConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CofferdamWalletBind__factory extends ContractFactory {
  constructor(...args: CofferdamWalletBindConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      CofferdamWalletBind & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): CofferdamWalletBind__factory {
    return super.connect(runner) as CofferdamWalletBind__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CofferdamWalletBindInterface {
    return new Interface(_abi) as CofferdamWalletBindInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): CofferdamWalletBind {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as CofferdamWalletBind;
  }
}
