/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace CofferdamSpotEscrow {
  export type SpotEscrowPolicyStruct = {
    funder: AddressLike;
    recruiter: AddressLike;
    workerNullifier: BytesLike;
    checkInTimeout: BigNumberish;
    checkOutTimeout: BigNumberish;
    witness: AddressLike;
    arbiter: AddressLike;
    killFeeBps: BigNumberish;
    amount: BigNumberish;
    termsHash: BytesLike;
    jobStartTime: BigNumberish;
    disputeWindow: BigNumberish;
  };

  export type SpotEscrowPolicyStructOutput = [
    funder: string,
    recruiter: string,
    workerNullifier: string,
    checkInTimeout: bigint,
    checkOutTimeout: bigint,
    witness: string,
    arbiter: string,
    killFeeBps: bigint,
    amount: bigint,
    termsHash: string,
    jobStartTime: bigint,
    disputeWindow: bigint
  ] & {
    funder: string;
    recruiter: string;
    workerNullifier: string;
    checkInTimeout: bigint;
    checkOutTimeout: bigint;
    witness: string;
    arbiter: string;
    killFeeBps: bigint;
    amount: bigint;
    termsHash: string;
    jobStartTime: bigint;
    disputeWindow: bigint;
  };
}

export interface CofferdamSpotEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "USDC"
      | "awardWorker"
      | "awardedWorker"
      | "cancel"
      | "checkIn"
      | "checkOut"
      | "checkedInAt"
      | "checkedOutAt"
      | "claimAfterCheckoutTimeout"
      | "claimAfterDisputeTimeout"
      | "createdAt"
      | "disputeReason"
      | "disputedAt"
      | "fund"
      | "fundedAmount"
      | "policy"
      | "raiseDispute"
      | "reclaimNoShow"
      | "refund"
      | "resolveDispute"
      | "selfWitnessed"
      | "setWitness"
      | "state"
      | "witnessHistory"
      | "witnessHistoryCount"
      | "worker"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DisputeResolved"
      | "EscrowDisputed"
      | "EscrowFunded"
      | "EscrowRefunded"
      | "EscrowReleased"
      | "EscrowStateChanged"
      | "KillFeePaid"
      | "WitnessAssigned"
      | "WitnessReplaced"
      | "WorkerAwarded"
  ): EventFragment;

  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "awardWorker",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "awardedWorker",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "cancel", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "checkIn",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "checkOut", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "checkedInAt",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkedOutAt",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimAfterCheckoutTimeout",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimAfterDisputeTimeout",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "createdAt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "disputeReason",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "disputedAt",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "fund", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "fundedAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "policy", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "raiseDispute",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reclaimNoShow",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "refund", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "selfWitnessed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setWitness",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "state", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "witnessHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "witnessHistoryCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "worker", values?: undefined): string;

  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "awardWorker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "awardedWorker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "checkIn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "checkOut", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkedInAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkedOutAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimAfterCheckoutTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimAfterDisputeTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createdAt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "disputeReason",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "disputedAt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fundedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "policy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "raiseDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reclaimNoShow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "selfWitnessed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setWitness", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "state", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "witnessHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "witnessHistoryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "worker", data: BytesLike): Result;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    worker: AddressLike,
    workerAmount: BigNumberish,
    funder: AddressLike,
    funderAmount: BigNumberish,
    arbiter: AddressLike
  ];
  export type OutputTuple = [
    worker: string,
    workerAmount: bigint,
    funder: string,
    funderAmount: bigint,
    arbiter: string
  ];
  export interface OutputObject {
    worker: string;
    workerAmount: bigint;
    funder: string;
    funderAmount: bigint;
    arbiter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowDisputedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    disputer: AddressLike,
    reason: BytesLike
  ];
  export type OutputTuple = [
    escrowId: bigint,
    disputer: string,
    reason: string
  ];
  export interface OutputObject {
    escrowId: bigint;
    disputer: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowFundedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    amount: BigNumberish,
    funder: AddressLike
  ];
  export type OutputTuple = [escrowId: bigint, amount: bigint, funder: string];
  export interface OutputObject {
    escrowId: bigint;
    amount: bigint;
    funder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowRefundedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    amount: BigNumberish,
    funder: AddressLike
  ];
  export type OutputTuple = [escrowId: bigint, amount: bigint, funder: string];
  export interface OutputObject {
    escrowId: bigint;
    amount: bigint;
    funder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowReleasedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    amount: BigNumberish,
    worker: AddressLike
  ];
  export type OutputTuple = [escrowId: bigint, amount: bigint, worker: string];
  export interface OutputObject {
    escrowId: bigint;
    amount: bigint;
    worker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowStateChangedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    fromState: BigNumberish,
    toState: BigNumberish,
    actor: AddressLike,
    timestamp: BigNumberish,
    proofHash: BytesLike
  ];
  export type OutputTuple = [
    escrowId: bigint,
    fromState: bigint,
    toState: bigint,
    actor: string,
    timestamp: bigint,
    proofHash: string
  ];
  export interface OutputObject {
    escrowId: bigint;
    fromState: bigint;
    toState: bigint;
    actor: string;
    timestamp: bigint;
    proofHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KillFeePaidEvent {
  export type InputTuple = [
    worker: AddressLike,
    amount: BigNumberish,
    funder: AddressLike
  ];
  export type OutputTuple = [worker: string, amount: bigint, funder: string];
  export interface OutputObject {
    worker: string;
    amount: bigint;
    funder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WitnessAssignedEvent {
  export type InputTuple = [witness: AddressLike, assignedBy: AddressLike];
  export type OutputTuple = [witness: string, assignedBy: string];
  export interface OutputObject {
    witness: string;
    assignedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WitnessReplacedEvent {
  export type InputTuple = [
    oldWitness: AddressLike,
    newWitness: AddressLike,
    replacedBy: AddressLike
  ];
  export type OutputTuple = [
    oldWitness: string,
    newWitness: string,
    replacedBy: string
  ];
  export interface OutputObject {
    oldWitness: string;
    newWitness: string;
    replacedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WorkerAwardedEvent {
  export type InputTuple = [worker: AddressLike, awardedBy: AddressLike];
  export type OutputTuple = [worker: string, awardedBy: string];
  export interface OutputObject {
    worker: string;
    awardedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CofferdamSpotEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): CofferdamSpotEscrow;
  waitForDeployment(): Promise<this>;

  interface: CofferdamSpotEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  USDC: TypedContractMethod<[], [string], "view">;

  awardWorker: TypedContractMethod<
    [_worker: AddressLike],
    [void],
    "nonpayable"
  >;

  awardedWorker: TypedContractMethod<[], [string], "view">;

  cancel: TypedContractMethod<[], [void], "nonpayable">;

  checkIn: TypedContractMethod<[_worker: AddressLike], [void], "nonpayable">;

  checkOut: TypedContractMethod<[], [void], "nonpayable">;

  checkedInAt: TypedContractMethod<[], [bigint], "view">;

  checkedOutAt: TypedContractMethod<[], [bigint], "view">;

  claimAfterCheckoutTimeout: TypedContractMethod<[], [void], "nonpayable">;

  claimAfterDisputeTimeout: TypedContractMethod<[], [void], "nonpayable">;

  createdAt: TypedContractMethod<[], [bigint], "view">;

  disputeReason: TypedContractMethod<[], [string], "view">;

  disputedAt: TypedContractMethod<[], [bigint], "view">;

  fund: TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  fundedAmount: TypedContractMethod<[], [bigint], "view">;

  policy: TypedContractMethod<
    [],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        funder: string;
        recruiter: string;
        workerNullifier: string;
        checkInTimeout: bigint;
        checkOutTimeout: bigint;
        witness: string;
        arbiter: string;
        killFeeBps: bigint;
        amount: bigint;
        termsHash: string;
        jobStartTime: bigint;
        disputeWindow: bigint;
      }
    ],
    "view"
  >;

  raiseDispute: TypedContractMethod<[_reason: BytesLike], [void], "nonpayable">;

  reclaimNoShow: TypedContractMethod<[], [void], "nonpayable">;

  refund: TypedContractMethod<[], [void], "nonpayable">;

  resolveDispute: TypedContractMethod<
    [_workerAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  selfWitnessed: TypedContractMethod<[], [boolean], "view">;

  setWitness: TypedContractMethod<
    [_newWitness: AddressLike],
    [void],
    "nonpayable"
  >;

  state: TypedContractMethod<[], [bigint], "view">;

  witnessHistory: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint] & {
        witness: string;
        assignedBy: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  witnessHistoryCount: TypedContractMethod<[], [bigint], "view">;

  worker: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "USDC"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "awardWorker"
  ): TypedContractMethod<[_worker: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "awardedWorker"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancel"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checkIn"
  ): TypedContractMethod<[_worker: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checkOut"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checkedInAt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "checkedOutAt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimAfterCheckoutTimeout"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimAfterDisputeTimeout"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createdAt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "disputeReason"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "disputedAt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "fund"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fundedAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "policy"
  ): TypedContractMethod<
    [],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        funder: string;
        recruiter: string;
        workerNullifier: string;
        checkInTimeout: bigint;
        checkOutTimeout: bigint;
        witness: string;
        arbiter: string;
        killFeeBps: bigint;
        amount: bigint;
        termsHash: string;
        jobStartTime: bigint;
        disputeWindow: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "raiseDispute"
  ): TypedContractMethod<[_reason: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reclaimNoShow"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<[_workerAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "selfWitnessed"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "setWitness"
  ): TypedContractMethod<[_newWitness: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "state"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "witnessHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint] & {
        witness: string;
        assignedBy: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "witnessHistoryCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "worker"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowDisputed"
  ): TypedContractEvent<
    EscrowDisputedEvent.InputTuple,
    EscrowDisputedEvent.OutputTuple,
    EscrowDisputedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowFunded"
  ): TypedContractEvent<
    EscrowFundedEvent.InputTuple,
    EscrowFundedEvent.OutputTuple,
    EscrowFundedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowRefunded"
  ): TypedContractEvent<
    EscrowRefundedEvent.InputTuple,
    EscrowRefundedEvent.OutputTuple,
    EscrowRefundedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowReleased"
  ): TypedContractEvent<
    EscrowReleasedEvent.InputTuple,
    EscrowReleasedEvent.OutputTuple,
    EscrowReleasedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowStateChanged"
  ): TypedContractEvent<
    EscrowStateChangedEvent.InputTuple,
    EscrowStateChangedEvent.OutputTuple,
    EscrowStateChangedEvent.OutputObject
  >;
  getEvent(
    key: "KillFeePaid"
  ): TypedContractEvent<
    KillFeePaidEvent.InputTuple,
    KillFeePaidEvent.OutputTuple,
    KillFeePaidEvent.OutputObject
  >;
  getEvent(
    key: "WitnessAssigned"
  ): TypedContractEvent<
    WitnessAssignedEvent.InputTuple,
    WitnessAssignedEvent.OutputTuple,
    WitnessAssignedEvent.OutputObject
  >;
  getEvent(
    key: "WitnessReplaced"
  ): TypedContractEvent<
    WitnessReplacedEvent.InputTuple,
    WitnessReplacedEvent.OutputTuple,
    WitnessReplacedEvent.OutputObject
  >;
  getEvent(
    key: "WorkerAwarded"
  ): TypedContractEvent<
    WorkerAwardedEvent.InputTuple,
    WorkerAwardedEvent.OutputTuple,
    WorkerAwardedEvent.OutputObject
  >;

  filters: {
    "DisputeResolved(address,uint256,address,uint256,address)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "EscrowDisputed(uint256,address,bytes32)": TypedContractEvent<
      EscrowDisputedEvent.InputTuple,
      EscrowDisputedEvent.OutputTuple,
      EscrowDisputedEvent.OutputObject
    >;
    EscrowDisputed: TypedContractEvent<
      EscrowDisputedEvent.InputTuple,
      EscrowDisputedEvent.OutputTuple,
      EscrowDisputedEvent.OutputObject
    >;

    "EscrowFunded(uint256,uint256,address)": TypedContractEvent<
      EscrowFundedEvent.InputTuple,
      EscrowFundedEvent.OutputTuple,
      EscrowFundedEvent.OutputObject
    >;
    EscrowFunded: TypedContractEvent<
      EscrowFundedEvent.InputTuple,
      EscrowFundedEvent.OutputTuple,
      EscrowFundedEvent.OutputObject
    >;

    "EscrowRefunded(uint256,uint256,address)": TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;
    EscrowRefunded: TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;

    "EscrowReleased(uint256,uint256,address)": TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;
    EscrowReleased: TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;

    "EscrowStateChanged(uint256,uint8,uint8,address,uint64,bytes32)": TypedContractEvent<
      EscrowStateChangedEvent.InputTuple,
      EscrowStateChangedEvent.OutputTuple,
      EscrowStateChangedEvent.OutputObject
    >;
    EscrowStateChanged: TypedContractEvent<
      EscrowStateChangedEvent.InputTuple,
      EscrowStateChangedEvent.OutputTuple,
      EscrowStateChangedEvent.OutputObject
    >;

    "KillFeePaid(address,uint256,address)": TypedContractEvent<
      KillFeePaidEvent.InputTuple,
      KillFeePaidEvent.OutputTuple,
      KillFeePaidEvent.OutputObject
    >;
    KillFeePaid: TypedContractEvent<
      KillFeePaidEvent.InputTuple,
      KillFeePaidEvent.OutputTuple,
      KillFeePaidEvent.OutputObject
    >;

    "WitnessAssigned(address,address)": TypedContractEvent<
      WitnessAssignedEvent.InputTuple,
      WitnessAssignedEvent.OutputTuple,
      WitnessAssignedEvent.OutputObject
    >;
    WitnessAssigned: TypedContractEvent<
      WitnessAssignedEvent.InputTuple,
      WitnessAssignedEvent.OutputTuple,
      WitnessAssignedEvent.OutputObject
    >;

    "WitnessReplaced(address,address,address)": TypedContractEvent<
      WitnessReplacedEvent.InputTuple,
      WitnessReplacedEvent.OutputTuple,
      WitnessReplacedEvent.OutputObject
    >;
    WitnessReplaced: TypedContractEvent<
      WitnessReplacedEvent.InputTuple,
      WitnessReplacedEvent.OutputTuple,
      WitnessReplacedEvent.OutputObject
    >;

    "WorkerAwarded(address,address)": TypedContractEvent<
      WorkerAwardedEvent.InputTuple,
      WorkerAwardedEvent.OutputTuple,
      WorkerAwardedEvent.OutputObject
    >;
    WorkerAwarded: TypedContractEvent<
      WorkerAwardedEvent.InputTuple,
      WorkerAwardedEvent.OutputTuple,
      WorkerAwardedEvent.OutputObject
    >;
  };
}
