/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace CofferdamSpotEscrow {
  export type SpotEscrowPolicyStruct = {
    funder: AddressLike;
    workerNullifier: BytesLike;
    checkInTimeout: BigNumberish;
    checkOutTimeout: BigNumberish;
    disputeWindow: BigNumberish;
    witness: AddressLike;
  };

  export type SpotEscrowPolicyStructOutput = [
    funder: string,
    workerNullifier: string,
    checkInTimeout: bigint,
    checkOutTimeout: bigint,
    disputeWindow: bigint,
    witness: string
  ] & {
    funder: string;
    workerNullifier: string;
    checkInTimeout: bigint;
    checkOutTimeout: bigint;
    disputeWindow: bigint;
    witness: string;
  };
}

export interface CofferdamSpotEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "USDC"
      | "cancel"
      | "checkIn"
      | "checkOut"
      | "checkedInAt"
      | "checkedOutAt"
      | "createdAt"
      | "fund"
      | "fundedAmount"
      | "policy"
      | "refund"
      | "release"
      | "state"
      | "worker"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EscrowDisputed"
      | "EscrowFunded"
      | "EscrowRefunded"
      | "EscrowReleased"
      | "EscrowStateChanged"
  ): EventFragment;

  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(functionFragment: "cancel", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "checkIn",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "checkOut", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "checkedInAt",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkedOutAt",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "createdAt", values?: undefined): string;
  encodeFunctionData(functionFragment: "fund", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "fundedAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "policy", values?: undefined): string;
  encodeFunctionData(functionFragment: "refund", values?: undefined): string;
  encodeFunctionData(functionFragment: "release", values?: undefined): string;
  encodeFunctionData(functionFragment: "state", values?: undefined): string;
  encodeFunctionData(functionFragment: "worker", values?: undefined): string;

  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "checkIn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "checkOut", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkedInAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkedOutAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createdAt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fundedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "policy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "state", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "worker", data: BytesLike): Result;
}

export namespace EscrowDisputedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    disputer: AddressLike,
    reason: BytesLike
  ];
  export type OutputTuple = [
    escrowId: bigint,
    disputer: string,
    reason: string
  ];
  export interface OutputObject {
    escrowId: bigint;
    disputer: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowFundedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    amount: BigNumberish,
    funder: AddressLike
  ];
  export type OutputTuple = [escrowId: bigint, amount: bigint, funder: string];
  export interface OutputObject {
    escrowId: bigint;
    amount: bigint;
    funder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowRefundedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    amount: BigNumberish,
    funder: AddressLike
  ];
  export type OutputTuple = [escrowId: bigint, amount: bigint, funder: string];
  export interface OutputObject {
    escrowId: bigint;
    amount: bigint;
    funder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowReleasedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    amount: BigNumberish,
    worker: AddressLike
  ];
  export type OutputTuple = [escrowId: bigint, amount: bigint, worker: string];
  export interface OutputObject {
    escrowId: bigint;
    amount: bigint;
    worker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowStateChangedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    fromState: BigNumberish,
    toState: BigNumberish,
    actor: AddressLike,
    timestamp: BigNumberish,
    proofHash: BytesLike
  ];
  export type OutputTuple = [
    escrowId: bigint,
    fromState: bigint,
    toState: bigint,
    actor: string,
    timestamp: bigint,
    proofHash: string
  ];
  export interface OutputObject {
    escrowId: bigint;
    fromState: bigint;
    toState: bigint;
    actor: string;
    timestamp: bigint;
    proofHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CofferdamSpotEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): CofferdamSpotEscrow;
  waitForDeployment(): Promise<this>;

  interface: CofferdamSpotEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  USDC: TypedContractMethod<[], [string], "view">;

  cancel: TypedContractMethod<[], [void], "nonpayable">;

  checkIn: TypedContractMethod<[_worker: AddressLike], [void], "nonpayable">;

  checkOut: TypedContractMethod<[], [void], "nonpayable">;

  checkedInAt: TypedContractMethod<[], [bigint], "view">;

  checkedOutAt: TypedContractMethod<[], [bigint], "view">;

  createdAt: TypedContractMethod<[], [bigint], "view">;

  fund: TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  fundedAmount: TypedContractMethod<[], [bigint], "view">;

  policy: TypedContractMethod<
    [],
    [
      [string, string, bigint, bigint, bigint, string] & {
        funder: string;
        workerNullifier: string;
        checkInTimeout: bigint;
        checkOutTimeout: bigint;
        disputeWindow: bigint;
        witness: string;
      }
    ],
    "view"
  >;

  refund: TypedContractMethod<[], [void], "nonpayable">;

  release: TypedContractMethod<[], [void], "nonpayable">;

  state: TypedContractMethod<[], [bigint], "view">;

  worker: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "USDC"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancel"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checkIn"
  ): TypedContractMethod<[_worker: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checkOut"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checkedInAt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "checkedOutAt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createdAt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "fund"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fundedAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "policy"
  ): TypedContractMethod<
    [],
    [
      [string, string, bigint, bigint, bigint, string] & {
        funder: string;
        workerNullifier: string;
        checkInTimeout: bigint;
        checkOutTimeout: bigint;
        disputeWindow: bigint;
        witness: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "release"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "state"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "worker"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "EscrowDisputed"
  ): TypedContractEvent<
    EscrowDisputedEvent.InputTuple,
    EscrowDisputedEvent.OutputTuple,
    EscrowDisputedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowFunded"
  ): TypedContractEvent<
    EscrowFundedEvent.InputTuple,
    EscrowFundedEvent.OutputTuple,
    EscrowFundedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowRefunded"
  ): TypedContractEvent<
    EscrowRefundedEvent.InputTuple,
    EscrowRefundedEvent.OutputTuple,
    EscrowRefundedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowReleased"
  ): TypedContractEvent<
    EscrowReleasedEvent.InputTuple,
    EscrowReleasedEvent.OutputTuple,
    EscrowReleasedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowStateChanged"
  ): TypedContractEvent<
    EscrowStateChangedEvent.InputTuple,
    EscrowStateChangedEvent.OutputTuple,
    EscrowStateChangedEvent.OutputObject
  >;

  filters: {
    "EscrowDisputed(uint256,address,bytes32)": TypedContractEvent<
      EscrowDisputedEvent.InputTuple,
      EscrowDisputedEvent.OutputTuple,
      EscrowDisputedEvent.OutputObject
    >;
    EscrowDisputed: TypedContractEvent<
      EscrowDisputedEvent.InputTuple,
      EscrowDisputedEvent.OutputTuple,
      EscrowDisputedEvent.OutputObject
    >;

    "EscrowFunded(uint256,uint256,address)": TypedContractEvent<
      EscrowFundedEvent.InputTuple,
      EscrowFundedEvent.OutputTuple,
      EscrowFundedEvent.OutputObject
    >;
    EscrowFunded: TypedContractEvent<
      EscrowFundedEvent.InputTuple,
      EscrowFundedEvent.OutputTuple,
      EscrowFundedEvent.OutputObject
    >;

    "EscrowRefunded(uint256,uint256,address)": TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;
    EscrowRefunded: TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;

    "EscrowReleased(uint256,uint256,address)": TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;
    EscrowReleased: TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;

    "EscrowStateChanged(uint256,uint8,uint8,address,uint64,bytes32)": TypedContractEvent<
      EscrowStateChangedEvent.InputTuple,
      EscrowStateChangedEvent.OutputTuple,
      EscrowStateChangedEvent.OutputObject
    >;
    EscrowStateChanged: TypedContractEvent<
      EscrowStateChangedEvent.InputTuple,
      EscrowStateChangedEvent.OutputTuple,
      EscrowStateChangedEvent.OutputObject
    >;
  };
}
