/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace CofferdamPayrollEscrow {
  export type PayrollEscrowPolicyStruct = {
    workerRole: BytesLike;
    payPeriodStart: BigNumberish;
    payPeriodEnd: BigNumberish;
    releaseDelay: BigNumberish;
    disputeWindow: BigNumberish;
    managerApproval: boolean;
  };

  export type PayrollEscrowPolicyStructOutput = [
    workerRole: string,
    payPeriodStart: bigint,
    payPeriodEnd: bigint,
    releaseDelay: bigint,
    disputeWindow: bigint,
    managerApproval: boolean
  ] & {
    workerRole: string;
    payPeriodStart: bigint;
    payPeriodEnd: bigint;
    releaseDelay: bigint;
    disputeWindow: bigint;
    managerApproval: boolean;
  };
}

export interface CofferdamPayrollEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "USDC"
      | "claim"
      | "companyOrgRoot"
      | "dispute"
      | "disputed"
      | "fund"
      | "fundedAmount"
      | "funder"
      | "managerApprove"
      | "managerApproved"
      | "policy"
      | "refund"
      | "state"
      | "worker"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EscrowDisputed"
      | "EscrowFunded"
      | "EscrowRefunded"
      | "EscrowReleased"
      | "EscrowStateChanged"
  ): EventFragment;

  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claim",
    values: [AddressLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "companyOrgRoot",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "dispute", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "disputed", values?: undefined): string;
  encodeFunctionData(functionFragment: "fund", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "fundedAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "funder", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "managerApprove",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "managerApproved",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "policy", values?: undefined): string;
  encodeFunctionData(functionFragment: "refund", values?: undefined): string;
  encodeFunctionData(functionFragment: "state", values?: undefined): string;
  encodeFunctionData(functionFragment: "worker", values?: undefined): string;

  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "companyOrgRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dispute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "disputed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fundedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "funder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "managerApprove",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "managerApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "policy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "state", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "worker", data: BytesLike): Result;
}

export namespace EscrowDisputedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    disputer: AddressLike,
    reason: BytesLike
  ];
  export type OutputTuple = [
    escrowId: bigint,
    disputer: string,
    reason: string
  ];
  export interface OutputObject {
    escrowId: bigint;
    disputer: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowFundedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    amount: BigNumberish,
    funder: AddressLike
  ];
  export type OutputTuple = [escrowId: bigint, amount: bigint, funder: string];
  export interface OutputObject {
    escrowId: bigint;
    amount: bigint;
    funder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowRefundedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    amount: BigNumberish,
    funder: AddressLike
  ];
  export type OutputTuple = [escrowId: bigint, amount: bigint, funder: string];
  export interface OutputObject {
    escrowId: bigint;
    amount: bigint;
    funder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowReleasedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    amount: BigNumberish,
    worker: AddressLike
  ];
  export type OutputTuple = [escrowId: bigint, amount: bigint, worker: string];
  export interface OutputObject {
    escrowId: bigint;
    amount: bigint;
    worker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowStateChangedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    fromState: BigNumberish,
    toState: BigNumberish,
    actor: AddressLike,
    timestamp: BigNumberish,
    proofHash: BytesLike
  ];
  export type OutputTuple = [
    escrowId: bigint,
    fromState: bigint,
    toState: bigint,
    actor: string,
    timestamp: bigint,
    proofHash: string
  ];
  export interface OutputObject {
    escrowId: bigint;
    fromState: bigint;
    toState: bigint;
    actor: string;
    timestamp: bigint;
    proofHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CofferdamPayrollEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): CofferdamPayrollEscrow;
  waitForDeployment(): Promise<this>;

  interface: CofferdamPayrollEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  USDC: TypedContractMethod<[], [string], "view">;

  claim: TypedContractMethod<
    [_worker: AddressLike, _merkleProof: BytesLike[]],
    [void],
    "nonpayable"
  >;

  companyOrgRoot: TypedContractMethod<[], [string], "view">;

  dispute: TypedContractMethod<[_reason: BytesLike], [void], "nonpayable">;

  disputed: TypedContractMethod<[], [boolean], "view">;

  fund: TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  fundedAmount: TypedContractMethod<[], [bigint], "view">;

  funder: TypedContractMethod<[], [string], "view">;

  managerApprove: TypedContractMethod<[], [void], "nonpayable">;

  managerApproved: TypedContractMethod<[], [boolean], "view">;

  policy: TypedContractMethod<
    [],
    [
      [string, bigint, bigint, bigint, bigint, boolean] & {
        workerRole: string;
        payPeriodStart: bigint;
        payPeriodEnd: bigint;
        releaseDelay: bigint;
        disputeWindow: bigint;
        managerApproval: boolean;
      }
    ],
    "view"
  >;

  refund: TypedContractMethod<[], [void], "nonpayable">;

  state: TypedContractMethod<[], [bigint], "view">;

  worker: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "USDC"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<
    [_worker: AddressLike, _merkleProof: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "companyOrgRoot"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "dispute"
  ): TypedContractMethod<[_reason: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "disputed"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "fund"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fundedAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "funder"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "managerApprove"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "managerApproved"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "policy"
  ): TypedContractMethod<
    [],
    [
      [string, bigint, bigint, bigint, bigint, boolean] & {
        workerRole: string;
        payPeriodStart: bigint;
        payPeriodEnd: bigint;
        releaseDelay: bigint;
        disputeWindow: bigint;
        managerApproval: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "state"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "worker"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "EscrowDisputed"
  ): TypedContractEvent<
    EscrowDisputedEvent.InputTuple,
    EscrowDisputedEvent.OutputTuple,
    EscrowDisputedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowFunded"
  ): TypedContractEvent<
    EscrowFundedEvent.InputTuple,
    EscrowFundedEvent.OutputTuple,
    EscrowFundedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowRefunded"
  ): TypedContractEvent<
    EscrowRefundedEvent.InputTuple,
    EscrowRefundedEvent.OutputTuple,
    EscrowRefundedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowReleased"
  ): TypedContractEvent<
    EscrowReleasedEvent.InputTuple,
    EscrowReleasedEvent.OutputTuple,
    EscrowReleasedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowStateChanged"
  ): TypedContractEvent<
    EscrowStateChangedEvent.InputTuple,
    EscrowStateChangedEvent.OutputTuple,
    EscrowStateChangedEvent.OutputObject
  >;

  filters: {
    "EscrowDisputed(uint256,address,bytes32)": TypedContractEvent<
      EscrowDisputedEvent.InputTuple,
      EscrowDisputedEvent.OutputTuple,
      EscrowDisputedEvent.OutputObject
    >;
    EscrowDisputed: TypedContractEvent<
      EscrowDisputedEvent.InputTuple,
      EscrowDisputedEvent.OutputTuple,
      EscrowDisputedEvent.OutputObject
    >;

    "EscrowFunded(uint256,uint256,address)": TypedContractEvent<
      EscrowFundedEvent.InputTuple,
      EscrowFundedEvent.OutputTuple,
      EscrowFundedEvent.OutputObject
    >;
    EscrowFunded: TypedContractEvent<
      EscrowFundedEvent.InputTuple,
      EscrowFundedEvent.OutputTuple,
      EscrowFundedEvent.OutputObject
    >;

    "EscrowRefunded(uint256,uint256,address)": TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;
    EscrowRefunded: TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;

    "EscrowReleased(uint256,uint256,address)": TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;
    EscrowReleased: TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;

    "EscrowStateChanged(uint256,uint8,uint8,address,uint64,bytes32)": TypedContractEvent<
      EscrowStateChangedEvent.InputTuple,
      EscrowStateChangedEvent.OutputTuple,
      EscrowStateChangedEvent.OutputObject
    >;
    EscrowStateChanged: TypedContractEvent<
      EscrowStateChangedEvent.InputTuple,
      EscrowStateChangedEvent.OutputTuple,
      EscrowStateChangedEvent.OutputObject
    >;
  };
}
