/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace CofferdamPayrollEscrow {
  export type PayrollEscrowPolicyStruct = {
    workerRole: BytesLike;
    payPeriodStart: BigNumberish;
    payPeriodEnd: BigNumberish;
    releaseDelay: BigNumberish;
    disputeWindow: BigNumberish;
    managerApproval: boolean;
  };

  export type PayrollEscrowPolicyStructOutput = [
    workerRole: string,
    payPeriodStart: bigint,
    payPeriodEnd: bigint,
    releaseDelay: bigint,
    disputeWindow: bigint,
    managerApproval: boolean
  ] & {
    workerRole: string;
    payPeriodStart: bigint;
    payPeriodEnd: bigint;
    releaseDelay: bigint;
    disputeWindow: bigint;
    managerApproval: boolean;
  };
}

export declare namespace CofferdamSpotEscrow {
  export type SpotEscrowPolicyStruct = {
    funder: AddressLike;
    recruiter: AddressLike;
    workerNullifier: BytesLike;
    checkInTimeout: BigNumberish;
    checkOutTimeout: BigNumberish;
    witness: AddressLike;
    arbiter: AddressLike;
    killFeeBps: BigNumberish;
    amount: BigNumberish;
    termsHash: BytesLike;
    jobStartTime: BigNumberish;
    disputeWindow: BigNumberish;
  };

  export type SpotEscrowPolicyStructOutput = [
    funder: string,
    recruiter: string,
    workerNullifier: string,
    checkInTimeout: bigint,
    checkOutTimeout: bigint,
    witness: string,
    arbiter: string,
    killFeeBps: bigint,
    amount: bigint,
    termsHash: string,
    jobStartTime: bigint,
    disputeWindow: bigint
  ] & {
    funder: string;
    recruiter: string;
    workerNullifier: string;
    checkInTimeout: bigint;
    checkOutTimeout: bigint;
    witness: string;
    arbiter: string;
    killFeeBps: bigint;
    amount: bigint;
    termsHash: string;
    jobStartTime: bigint;
    disputeWindow: bigint;
  };
}

export interface EscrowFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "USDC"
      | "authorize"
      | "authorizedCallers"
      | "createPayrollEscrow"
      | "createSpotEscrow"
      | "owner"
      | "predictSpotEscrowAddress"
      | "revoke"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CallerAuthorized"
      | "CallerRevoked"
      | "PayrollEscrowCreated"
      | "SpotEscrowCreated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "authorize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedCallers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createPayrollEscrow",
    values: [
      AddressLike,
      BytesLike,
      CofferdamPayrollEscrow.PayrollEscrowPolicyStruct,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createSpotEscrow",
    values: [CofferdamSpotEscrow.SpotEscrowPolicyStruct, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "predictSpotEscrowAddress",
    values: [CofferdamSpotEscrow.SpotEscrowPolicyStruct, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "revoke", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "authorize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorizedCallers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPayrollEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSpotEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "predictSpotEscrowAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revoke", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace CallerAuthorizedEvent {
  export type InputTuple = [caller: AddressLike, authorizedBy: AddressLike];
  export type OutputTuple = [caller: string, authorizedBy: string];
  export interface OutputObject {
    caller: string;
    authorizedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CallerRevokedEvent {
  export type InputTuple = [caller: AddressLike, revokedBy: AddressLike];
  export type OutputTuple = [caller: string, revokedBy: string];
  export interface OutputObject {
    caller: string;
    revokedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayrollEscrowCreatedEvent {
  export type InputTuple = [
    escrow: AddressLike,
    funder: AddressLike,
    workerRole: BytesLike,
    payPeriodEnd: BigNumberish
  ];
  export type OutputTuple = [
    escrow: string,
    funder: string,
    workerRole: string,
    payPeriodEnd: bigint
  ];
  export interface OutputObject {
    escrow: string;
    funder: string;
    workerRole: string;
    payPeriodEnd: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SpotEscrowCreatedEvent {
  export type InputTuple = [
    escrow: AddressLike,
    funder: AddressLike,
    recruiter: AddressLike,
    workerNullifier: BytesLike,
    witness: AddressLike
  ];
  export type OutputTuple = [
    escrow: string,
    funder: string,
    recruiter: string,
    workerNullifier: string,
    witness: string
  ];
  export interface OutputObject {
    escrow: string;
    funder: string;
    recruiter: string;
    workerNullifier: string;
    witness: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EscrowFactory extends BaseContract {
  connect(runner?: ContractRunner | null): EscrowFactory;
  waitForDeployment(): Promise<this>;

  interface: EscrowFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  USDC: TypedContractMethod<[], [string], "view">;

  authorize: TypedContractMethod<[_caller: AddressLike], [void], "nonpayable">;

  authorizedCallers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  createPayrollEscrow: TypedContractMethod<
    [
      _funder: AddressLike,
      _companyOrgRoot: BytesLike,
      _policy: CofferdamPayrollEscrow.PayrollEscrowPolicyStruct,
      _salt: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  createSpotEscrow: TypedContractMethod<
    [_policy: CofferdamSpotEscrow.SpotEscrowPolicyStruct, _salt: BytesLike],
    [string],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  predictSpotEscrowAddress: TypedContractMethod<
    [_policy: CofferdamSpotEscrow.SpotEscrowPolicyStruct, _salt: BytesLike],
    [string],
    "view"
  >;

  revoke: TypedContractMethod<[_caller: AddressLike], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [_newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "USDC"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "authorize"
  ): TypedContractMethod<[_caller: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedCallers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "createPayrollEscrow"
  ): TypedContractMethod<
    [
      _funder: AddressLike,
      _companyOrgRoot: BytesLike,
      _policy: CofferdamPayrollEscrow.PayrollEscrowPolicyStruct,
      _salt: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createSpotEscrow"
  ): TypedContractMethod<
    [_policy: CofferdamSpotEscrow.SpotEscrowPolicyStruct, _salt: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "predictSpotEscrowAddress"
  ): TypedContractMethod<
    [_policy: CofferdamSpotEscrow.SpotEscrowPolicyStruct, _salt: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "revoke"
  ): TypedContractMethod<[_caller: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[_newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CallerAuthorized"
  ): TypedContractEvent<
    CallerAuthorizedEvent.InputTuple,
    CallerAuthorizedEvent.OutputTuple,
    CallerAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "CallerRevoked"
  ): TypedContractEvent<
    CallerRevokedEvent.InputTuple,
    CallerRevokedEvent.OutputTuple,
    CallerRevokedEvent.OutputObject
  >;
  getEvent(
    key: "PayrollEscrowCreated"
  ): TypedContractEvent<
    PayrollEscrowCreatedEvent.InputTuple,
    PayrollEscrowCreatedEvent.OutputTuple,
    PayrollEscrowCreatedEvent.OutputObject
  >;
  getEvent(
    key: "SpotEscrowCreated"
  ): TypedContractEvent<
    SpotEscrowCreatedEvent.InputTuple,
    SpotEscrowCreatedEvent.OutputTuple,
    SpotEscrowCreatedEvent.OutputObject
  >;

  filters: {
    "CallerAuthorized(address,address)": TypedContractEvent<
      CallerAuthorizedEvent.InputTuple,
      CallerAuthorizedEvent.OutputTuple,
      CallerAuthorizedEvent.OutputObject
    >;
    CallerAuthorized: TypedContractEvent<
      CallerAuthorizedEvent.InputTuple,
      CallerAuthorizedEvent.OutputTuple,
      CallerAuthorizedEvent.OutputObject
    >;

    "CallerRevoked(address,address)": TypedContractEvent<
      CallerRevokedEvent.InputTuple,
      CallerRevokedEvent.OutputTuple,
      CallerRevokedEvent.OutputObject
    >;
    CallerRevoked: TypedContractEvent<
      CallerRevokedEvent.InputTuple,
      CallerRevokedEvent.OutputTuple,
      CallerRevokedEvent.OutputObject
    >;

    "PayrollEscrowCreated(address,address,bytes32,uint48)": TypedContractEvent<
      PayrollEscrowCreatedEvent.InputTuple,
      PayrollEscrowCreatedEvent.OutputTuple,
      PayrollEscrowCreatedEvent.OutputObject
    >;
    PayrollEscrowCreated: TypedContractEvent<
      PayrollEscrowCreatedEvent.InputTuple,
      PayrollEscrowCreatedEvent.OutputTuple,
      PayrollEscrowCreatedEvent.OutputObject
    >;

    "SpotEscrowCreated(address,address,address,bytes32,address)": TypedContractEvent<
      SpotEscrowCreatedEvent.InputTuple,
      SpotEscrowCreatedEvent.OutputTuple,
      SpotEscrowCreatedEvent.OutputObject
    >;
    SpotEscrowCreated: TypedContractEvent<
      SpotEscrowCreatedEvent.InputTuple,
      SpotEscrowCreatedEvent.OutputTuple,
      SpotEscrowCreatedEvent.OutputObject
    >;
  };
}
