/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace CofferdamPayrollEscrow {
  export type PayrollEscrowPolicyStruct = {
    workerRole: BytesLike;
    payPeriodStart: BigNumberish;
    payPeriodEnd: BigNumberish;
    releaseDelay: BigNumberish;
    disputeWindow: BigNumberish;
    managerApproval: boolean;
  };

  export type PayrollEscrowPolicyStructOutput = [
    workerRole: string,
    payPeriodStart: bigint,
    payPeriodEnd: bigint,
    releaseDelay: bigint,
    disputeWindow: bigint,
    managerApproval: boolean
  ] & {
    workerRole: string;
    payPeriodStart: bigint;
    payPeriodEnd: bigint;
    releaseDelay: bigint;
    disputeWindow: bigint;
    managerApproval: boolean;
  };
}

export declare namespace CofferdamSpotEscrow {
  export type SpotEscrowPolicyStruct = {
    funder: AddressLike;
    workerNullifier: BytesLike;
    checkInTimeout: BigNumberish;
    checkOutTimeout: BigNumberish;
    disputeWindow: BigNumberish;
    witness: AddressLike;
  };

  export type SpotEscrowPolicyStructOutput = [
    funder: string,
    workerNullifier: string,
    checkInTimeout: bigint,
    checkOutTimeout: bigint,
    disputeWindow: bigint,
    witness: string
  ] & {
    funder: string;
    workerNullifier: string;
    checkInTimeout: bigint;
    checkOutTimeout: bigint;
    disputeWindow: bigint;
    witness: string;
  };
}

export interface EscrowFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "USDC" | "createPayrollEscrow" | "createSpotEscrow"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "PayrollEscrowCreated" | "SpotEscrowCreated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createPayrollEscrow",
    values: [
      AddressLike,
      BytesLike,
      CofferdamPayrollEscrow.PayrollEscrowPolicyStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createSpotEscrow",
    values: [CofferdamSpotEscrow.SpotEscrowPolicyStruct]
  ): string;

  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createPayrollEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSpotEscrow",
    data: BytesLike
  ): Result;
}

export namespace PayrollEscrowCreatedEvent {
  export type InputTuple = [
    escrow: AddressLike,
    funder: AddressLike,
    workerRole: BytesLike,
    payPeriodEnd: BigNumberish
  ];
  export type OutputTuple = [
    escrow: string,
    funder: string,
    workerRole: string,
    payPeriodEnd: bigint
  ];
  export interface OutputObject {
    escrow: string;
    funder: string;
    workerRole: string;
    payPeriodEnd: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SpotEscrowCreatedEvent {
  export type InputTuple = [
    escrow: AddressLike,
    funder: AddressLike,
    workerNullifier: BytesLike
  ];
  export type OutputTuple = [
    escrow: string,
    funder: string,
    workerNullifier: string
  ];
  export interface OutputObject {
    escrow: string;
    funder: string;
    workerNullifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EscrowFactory extends BaseContract {
  connect(runner?: ContractRunner | null): EscrowFactory;
  waitForDeployment(): Promise<this>;

  interface: EscrowFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  USDC: TypedContractMethod<[], [string], "view">;

  createPayrollEscrow: TypedContractMethod<
    [
      _funder: AddressLike,
      _companyOrgRoot: BytesLike,
      _policy: CofferdamPayrollEscrow.PayrollEscrowPolicyStruct
    ],
    [string],
    "nonpayable"
  >;

  createSpotEscrow: TypedContractMethod<
    [_policy: CofferdamSpotEscrow.SpotEscrowPolicyStruct],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "USDC"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createPayrollEscrow"
  ): TypedContractMethod<
    [
      _funder: AddressLike,
      _companyOrgRoot: BytesLike,
      _policy: CofferdamPayrollEscrow.PayrollEscrowPolicyStruct
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createSpotEscrow"
  ): TypedContractMethod<
    [_policy: CofferdamSpotEscrow.SpotEscrowPolicyStruct],
    [string],
    "nonpayable"
  >;

  getEvent(
    key: "PayrollEscrowCreated"
  ): TypedContractEvent<
    PayrollEscrowCreatedEvent.InputTuple,
    PayrollEscrowCreatedEvent.OutputTuple,
    PayrollEscrowCreatedEvent.OutputObject
  >;
  getEvent(
    key: "SpotEscrowCreated"
  ): TypedContractEvent<
    SpotEscrowCreatedEvent.InputTuple,
    SpotEscrowCreatedEvent.OutputTuple,
    SpotEscrowCreatedEvent.OutputObject
  >;

  filters: {
    "PayrollEscrowCreated(address,address,bytes32,uint48)": TypedContractEvent<
      PayrollEscrowCreatedEvent.InputTuple,
      PayrollEscrowCreatedEvent.OutputTuple,
      PayrollEscrowCreatedEvent.OutputObject
    >;
    PayrollEscrowCreated: TypedContractEvent<
      PayrollEscrowCreatedEvent.InputTuple,
      PayrollEscrowCreatedEvent.OutputTuple,
      PayrollEscrowCreatedEvent.OutputObject
    >;

    "SpotEscrowCreated(address,address,bytes32)": TypedContractEvent<
      SpotEscrowCreatedEvent.InputTuple,
      SpotEscrowCreatedEvent.OutputTuple,
      SpotEscrowCreatedEvent.OutputObject
    >;
    SpotEscrowCreated: TypedContractEvent<
      SpotEscrowCreatedEvent.InputTuple,
      SpotEscrowCreatedEvent.OutputTuple,
      SpotEscrowCreatedEvent.OutputObject
    >;
  };
}
