/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../../../common";

export interface IEscrowInterface extends Interface {
  getEvent(
    nameOrSignatureOrTopic:
      | "EscrowDisputed"
      | "EscrowFunded"
      | "EscrowRefunded"
      | "EscrowReleased"
      | "EscrowStateChanged"
  ): EventFragment;
}

export namespace EscrowDisputedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    disputer: AddressLike,
    reason: BytesLike
  ];
  export type OutputTuple = [
    escrowId: bigint,
    disputer: string,
    reason: string
  ];
  export interface OutputObject {
    escrowId: bigint;
    disputer: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowFundedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    amount: BigNumberish,
    funder: AddressLike
  ];
  export type OutputTuple = [escrowId: bigint, amount: bigint, funder: string];
  export interface OutputObject {
    escrowId: bigint;
    amount: bigint;
    funder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowRefundedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    amount: BigNumberish,
    funder: AddressLike
  ];
  export type OutputTuple = [escrowId: bigint, amount: bigint, funder: string];
  export interface OutputObject {
    escrowId: bigint;
    amount: bigint;
    funder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowReleasedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    amount: BigNumberish,
    worker: AddressLike
  ];
  export type OutputTuple = [escrowId: bigint, amount: bigint, worker: string];
  export interface OutputObject {
    escrowId: bigint;
    amount: bigint;
    worker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowStateChangedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    fromState: BigNumberish,
    toState: BigNumberish,
    actor: AddressLike,
    timestamp: BigNumberish,
    proofHash: BytesLike
  ];
  export type OutputTuple = [
    escrowId: bigint,
    fromState: bigint,
    toState: bigint,
    actor: string,
    timestamp: bigint,
    proofHash: string
  ];
  export interface OutputObject {
    escrowId: bigint;
    fromState: bigint;
    toState: bigint;
    actor: string;
    timestamp: bigint;
    proofHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): IEscrow;
  waitForDeployment(): Promise<this>;

  interface: IEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "EscrowDisputed"
  ): TypedContractEvent<
    EscrowDisputedEvent.InputTuple,
    EscrowDisputedEvent.OutputTuple,
    EscrowDisputedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowFunded"
  ): TypedContractEvent<
    EscrowFundedEvent.InputTuple,
    EscrowFundedEvent.OutputTuple,
    EscrowFundedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowRefunded"
  ): TypedContractEvent<
    EscrowRefundedEvent.InputTuple,
    EscrowRefundedEvent.OutputTuple,
    EscrowRefundedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowReleased"
  ): TypedContractEvent<
    EscrowReleasedEvent.InputTuple,
    EscrowReleasedEvent.OutputTuple,
    EscrowReleasedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowStateChanged"
  ): TypedContractEvent<
    EscrowStateChangedEvent.InputTuple,
    EscrowStateChangedEvent.OutputTuple,
    EscrowStateChangedEvent.OutputObject
  >;

  filters: {
    "EscrowDisputed(uint256,address,bytes32)": TypedContractEvent<
      EscrowDisputedEvent.InputTuple,
      EscrowDisputedEvent.OutputTuple,
      EscrowDisputedEvent.OutputObject
    >;
    EscrowDisputed: TypedContractEvent<
      EscrowDisputedEvent.InputTuple,
      EscrowDisputedEvent.OutputTuple,
      EscrowDisputedEvent.OutputObject
    >;

    "EscrowFunded(uint256,uint256,address)": TypedContractEvent<
      EscrowFundedEvent.InputTuple,
      EscrowFundedEvent.OutputTuple,
      EscrowFundedEvent.OutputObject
    >;
    EscrowFunded: TypedContractEvent<
      EscrowFundedEvent.InputTuple,
      EscrowFundedEvent.OutputTuple,
      EscrowFundedEvent.OutputObject
    >;

    "EscrowRefunded(uint256,uint256,address)": TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;
    EscrowRefunded: TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;

    "EscrowReleased(uint256,uint256,address)": TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;
    EscrowReleased: TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;

    "EscrowStateChanged(uint256,uint8,uint8,address,uint64,bytes32)": TypedContractEvent<
      EscrowStateChangedEvent.InputTuple,
      EscrowStateChangedEvent.OutputTuple,
      EscrowStateChangedEvent.OutputObject
    >;
    EscrowStateChanged: TypedContractEvent<
      EscrowStateChangedEvent.InputTuple,
      EscrowStateChangedEvent.OutputTuple,
      EscrowStateChangedEvent.OutputObject
    >;
  };
}
