/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISelfGroth16Verifier,
  ISelfGroth16VerifierInterface,
} from "../../../contracts/self/ISelfGroth16Verifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[2]",
        name: "a",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[2][2]",
        name: "b",
        type: "uint256[2][2]",
      },
      {
        internalType: "uint256[2]",
        name: "c",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[21]",
        name: "pubSignals",
        type: "uint256[21]",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ISelfGroth16Verifier__factory {
  static readonly abi = _abi;
  static createInterface(): ISelfGroth16VerifierInterface {
    return new Interface(_abi) as ISelfGroth16VerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISelfGroth16Verifier {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ISelfGroth16Verifier;
  }
}
