/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CofferdamCompanyRegistry__factory } from "./CofferdamCompanyRegistry__factory";
export { CofferdamCorporateRegistry__factory } from "./CofferdamCorporateRegistry__factory";
