/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface CofferdamCorporateRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "delegateWitness"
      | "delegatedWitnesses"
      | "getOrgRoot"
      | "isCompanyPaused"
      | "isWitnessDelegated"
      | "orgRoots"
      | "pauseCompany"
      | "pausedCompanies"
      | "revokeWitness"
      | "unpauseCompany"
      | "updateOrgRoot"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CompanyPaused"
      | "CompanyUnpaused"
      | "OrgRootUpdated"
      | "WitnessDelegated"
      | "WitnessRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "delegateWitness",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "delegatedWitnesses",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrgRoot",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isCompanyPaused",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isWitnessDelegated",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "orgRoots", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "pauseCompany",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pausedCompanies",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeWitness",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unpauseCompany",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateOrgRoot",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "delegateWitness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "delegatedWitnesses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOrgRoot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isCompanyPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWitnessDelegated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "orgRoots", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauseCompany",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pausedCompanies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeWitness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unpauseCompany",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateOrgRoot",
    data: BytesLike
  ): Result;
}

export namespace CompanyPausedEvent {
  export type InputTuple = [companyAnchor: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [companyAnchor: string, timestamp: bigint];
  export interface OutputObject {
    companyAnchor: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CompanyUnpausedEvent {
  export type InputTuple = [companyAnchor: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [companyAnchor: string, timestamp: bigint];
  export interface OutputObject {
    companyAnchor: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrgRootUpdatedEvent {
  export type InputTuple = [
    companyAnchor: BytesLike,
    newRoot: BytesLike,
    generation: BigNumberish,
    updatedAt: BigNumberish
  ];
  export type OutputTuple = [
    companyAnchor: string,
    newRoot: string,
    generation: bigint,
    updatedAt: bigint
  ];
  export interface OutputObject {
    companyAnchor: string;
    newRoot: string;
    generation: bigint;
    updatedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WitnessDelegatedEvent {
  export type InputTuple = [companyAnchor: BytesLike, witness: AddressLike];
  export type OutputTuple = [companyAnchor: string, witness: string];
  export interface OutputObject {
    companyAnchor: string;
    witness: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WitnessRevokedEvent {
  export type InputTuple = [companyAnchor: BytesLike, witness: AddressLike];
  export type OutputTuple = [companyAnchor: string, witness: string];
  export interface OutputObject {
    companyAnchor: string;
    witness: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CofferdamCorporateRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CofferdamCorporateRegistry;
  waitForDeployment(): Promise<this>;

  interface: CofferdamCorporateRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  delegateWitness: TypedContractMethod<
    [_companyAnchor: BytesLike, _witness: AddressLike],
    [void],
    "nonpayable"
  >;

  delegatedWitnesses: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  getOrgRoot: TypedContractMethod<
    [_companyAnchor: BytesLike],
    [
      [string, bigint, bigint] & {
        root: string;
        generation: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;

  isCompanyPaused: TypedContractMethod<
    [_companyAnchor: BytesLike],
    [boolean],
    "view"
  >;

  isWitnessDelegated: TypedContractMethod<
    [_companyAnchor: BytesLike, _witness: AddressLike],
    [boolean],
    "view"
  >;

  orgRoots: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint] & {
        root: string;
        generation: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;

  pauseCompany: TypedContractMethod<
    [_companyAnchor: BytesLike],
    [void],
    "nonpayable"
  >;

  pausedCompanies: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  revokeWitness: TypedContractMethod<
    [_companyAnchor: BytesLike, _witness: AddressLike],
    [void],
    "nonpayable"
  >;

  unpauseCompany: TypedContractMethod<
    [_companyAnchor: BytesLike],
    [void],
    "nonpayable"
  >;

  updateOrgRoot: TypedContractMethod<
    [_companyAnchor: BytesLike, _newRoot: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "delegateWitness"
  ): TypedContractMethod<
    [_companyAnchor: BytesLike, _witness: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "delegatedWitnesses"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOrgRoot"
  ): TypedContractMethod<
    [_companyAnchor: BytesLike],
    [
      [string, bigint, bigint] & {
        root: string;
        generation: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isCompanyPaused"
  ): TypedContractMethod<[_companyAnchor: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isWitnessDelegated"
  ): TypedContractMethod<
    [_companyAnchor: BytesLike, _witness: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "orgRoots"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint] & {
        root: string;
        generation: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pauseCompany"
  ): TypedContractMethod<[_companyAnchor: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "pausedCompanies"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "revokeWitness"
  ): TypedContractMethod<
    [_companyAnchor: BytesLike, _witness: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unpauseCompany"
  ): TypedContractMethod<[_companyAnchor: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateOrgRoot"
  ): TypedContractMethod<
    [_companyAnchor: BytesLike, _newRoot: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CompanyPaused"
  ): TypedContractEvent<
    CompanyPausedEvent.InputTuple,
    CompanyPausedEvent.OutputTuple,
    CompanyPausedEvent.OutputObject
  >;
  getEvent(
    key: "CompanyUnpaused"
  ): TypedContractEvent<
    CompanyUnpausedEvent.InputTuple,
    CompanyUnpausedEvent.OutputTuple,
    CompanyUnpausedEvent.OutputObject
  >;
  getEvent(
    key: "OrgRootUpdated"
  ): TypedContractEvent<
    OrgRootUpdatedEvent.InputTuple,
    OrgRootUpdatedEvent.OutputTuple,
    OrgRootUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "WitnessDelegated"
  ): TypedContractEvent<
    WitnessDelegatedEvent.InputTuple,
    WitnessDelegatedEvent.OutputTuple,
    WitnessDelegatedEvent.OutputObject
  >;
  getEvent(
    key: "WitnessRevoked"
  ): TypedContractEvent<
    WitnessRevokedEvent.InputTuple,
    WitnessRevokedEvent.OutputTuple,
    WitnessRevokedEvent.OutputObject
  >;

  filters: {
    "CompanyPaused(bytes32,uint48)": TypedContractEvent<
      CompanyPausedEvent.InputTuple,
      CompanyPausedEvent.OutputTuple,
      CompanyPausedEvent.OutputObject
    >;
    CompanyPaused: TypedContractEvent<
      CompanyPausedEvent.InputTuple,
      CompanyPausedEvent.OutputTuple,
      CompanyPausedEvent.OutputObject
    >;

    "CompanyUnpaused(bytes32,uint48)": TypedContractEvent<
      CompanyUnpausedEvent.InputTuple,
      CompanyUnpausedEvent.OutputTuple,
      CompanyUnpausedEvent.OutputObject
    >;
    CompanyUnpaused: TypedContractEvent<
      CompanyUnpausedEvent.InputTuple,
      CompanyUnpausedEvent.OutputTuple,
      CompanyUnpausedEvent.OutputObject
    >;

    "OrgRootUpdated(bytes32,bytes32,uint32,uint48)": TypedContractEvent<
      OrgRootUpdatedEvent.InputTuple,
      OrgRootUpdatedEvent.OutputTuple,
      OrgRootUpdatedEvent.OutputObject
    >;
    OrgRootUpdated: TypedContractEvent<
      OrgRootUpdatedEvent.InputTuple,
      OrgRootUpdatedEvent.OutputTuple,
      OrgRootUpdatedEvent.OutputObject
    >;

    "WitnessDelegated(bytes32,address)": TypedContractEvent<
      WitnessDelegatedEvent.InputTuple,
      WitnessDelegatedEvent.OutputTuple,
      WitnessDelegatedEvent.OutputObject
    >;
    WitnessDelegated: TypedContractEvent<
      WitnessDelegatedEvent.InputTuple,
      WitnessDelegatedEvent.OutputTuple,
      WitnessDelegatedEvent.OutputObject
    >;

    "WitnessRevoked(bytes32,address)": TypedContractEvent<
      WitnessRevokedEvent.InputTuple,
      WitnessRevokedEvent.OutputTuple,
      WitnessRevokedEvent.OutputObject
    >;
    WitnessRevoked: TypedContractEvent<
      WitnessRevokedEvent.InputTuple,
      WitnessRevokedEvent.OutputTuple,
      WitnessRevokedEvent.OutputObject
    >;
  };
}
