/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface CofferdamCompanyRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "companies"
      | "domainCount"
      | "domains"
      | "getCompanyWallet"
      | "isCompanyPaused"
      | "pauseCompany"
      | "registerCompany"
      | "unpauseCompany"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CompanyPaused"
      | "CompanyRegistered"
      | "CompanyUnpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "companies",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "domainCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "domains",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCompanyWallet",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isCompanyPaused",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pauseCompany",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerCompany",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unpauseCompany",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "companies", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "domainCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "domains", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCompanyWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isCompanyPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pauseCompany",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerCompany",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unpauseCompany",
    data: BytesLike
  ): Result;
}

export namespace CompanyPausedEvent {
  export type InputTuple = [domainHash: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [domainHash: string, timestamp: bigint];
  export interface OutputObject {
    domainHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CompanyRegisteredEvent {
  export type InputTuple = [
    companyAnchor: BytesLike,
    domainHash: BytesLike,
    companyWallet: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    companyAnchor: string,
    domainHash: string,
    companyWallet: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    companyAnchor: string;
    domainHash: string;
    companyWallet: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CompanyUnpausedEvent {
  export type InputTuple = [domainHash: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [domainHash: string, timestamp: bigint];
  export interface OutputObject {
    domainHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CofferdamCompanyRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CofferdamCompanyRegistry;
  waitForDeployment(): Promise<this>;

  interface: CofferdamCompanyRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  companies: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, boolean, bigint] & {
        companyAnchor: string;
        domainHash: string;
        companyWallet: string;
        paused: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  domainCount: TypedContractMethod<[], [bigint], "view">;

  domains: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getCompanyWallet: TypedContractMethod<
    [_canonicalDomainHash: BytesLike],
    [string],
    "view"
  >;

  isCompanyPaused: TypedContractMethod<
    [_canonicalDomainHash: BytesLike],
    [boolean],
    "view"
  >;

  pauseCompany: TypedContractMethod<
    [_canonicalDomainHash: BytesLike],
    [void],
    "nonpayable"
  >;

  registerCompany: TypedContractMethod<
    [
      _canonicalDomainHash: BytesLike,
      _companyAnchor: BytesLike,
      _dnsProofHash: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  unpauseCompany: TypedContractMethod<
    [_canonicalDomainHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "companies"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, boolean, bigint] & {
        companyAnchor: string;
        domainHash: string;
        companyWallet: string;
        paused: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "domainCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "domains"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getCompanyWallet"
  ): TypedContractMethod<[_canonicalDomainHash: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "isCompanyPaused"
  ): TypedContractMethod<[_canonicalDomainHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "pauseCompany"
  ): TypedContractMethod<
    [_canonicalDomainHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerCompany"
  ): TypedContractMethod<
    [
      _canonicalDomainHash: BytesLike,
      _companyAnchor: BytesLike,
      _dnsProofHash: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unpauseCompany"
  ): TypedContractMethod<
    [_canonicalDomainHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CompanyPaused"
  ): TypedContractEvent<
    CompanyPausedEvent.InputTuple,
    CompanyPausedEvent.OutputTuple,
    CompanyPausedEvent.OutputObject
  >;
  getEvent(
    key: "CompanyRegistered"
  ): TypedContractEvent<
    CompanyRegisteredEvent.InputTuple,
    CompanyRegisteredEvent.OutputTuple,
    CompanyRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "CompanyUnpaused"
  ): TypedContractEvent<
    CompanyUnpausedEvent.InputTuple,
    CompanyUnpausedEvent.OutputTuple,
    CompanyUnpausedEvent.OutputObject
  >;

  filters: {
    "CompanyPaused(bytes32,uint256)": TypedContractEvent<
      CompanyPausedEvent.InputTuple,
      CompanyPausedEvent.OutputTuple,
      CompanyPausedEvent.OutputObject
    >;
    CompanyPaused: TypedContractEvent<
      CompanyPausedEvent.InputTuple,
      CompanyPausedEvent.OutputTuple,
      CompanyPausedEvent.OutputObject
    >;

    "CompanyRegistered(bytes32,bytes32,address,uint256)": TypedContractEvent<
      CompanyRegisteredEvent.InputTuple,
      CompanyRegisteredEvent.OutputTuple,
      CompanyRegisteredEvent.OutputObject
    >;
    CompanyRegistered: TypedContractEvent<
      CompanyRegisteredEvent.InputTuple,
      CompanyRegisteredEvent.OutputTuple,
      CompanyRegisteredEvent.OutputObject
    >;

    "CompanyUnpaused(bytes32,uint256)": TypedContractEvent<
      CompanyUnpausedEvent.InputTuple,
      CompanyUnpausedEvent.OutputTuple,
      CompanyUnpausedEvent.OutputObject
    >;
    CompanyUnpaused: TypedContractEvent<
      CompanyUnpausedEvent.InputTuple,
      CompanyUnpausedEvent.OutputTuple,
      CompanyUnpausedEvent.OutputObject
    >;
  };
}
