/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CofferdamCompanyRegistry } from "./CofferdamCompanyRegistry";
export type { CofferdamCorporateRegistry } from "./CofferdamCorporateRegistry";
