/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAuthorityModule,
  IAuthorityModuleInterface,
} from "../../../contracts/interfaces/IAuthorityModule";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "digest",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "config",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
    ],
    name: "isValidSignature",
    outputs: [
      {
        internalType: "bool",
        name: "ok",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "kind",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "tier",
    outputs: [
      {
        internalType: "enum Tier",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAuthorityModule__factory {
  static readonly abi = _abi;
  static createInterface(): IAuthorityModuleInterface {
    return new Interface(_abi) as IAuthorityModuleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAuthorityModule {
    return new Contract(address, _abi, runner) as unknown as IAuthorityModule;
  }
}
