/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ISelfGroth16Verifier } from "./ISelfGroth16Verifier";
export type { NullifierRegistry } from "./NullifierRegistry";
export type { SelfAttesterRegistry } from "./SelfAttesterRegistry";
