/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface NullifierRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "accountToNullifier"
      | "attesterMessageHash"
      | "attesterRegistry"
      | "expectedScope"
      | "isAccountBound"
      | "isNullifierBound"
      | "nullifierToAccount"
      | "verifier"
      | "verifyAndBind"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "NullifierBound"): EventFragment;

  encodeFunctionData(
    functionFragment: "accountToNullifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "attesterMessageHash",
    values: [AddressLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "attesterRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "expectedScope",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAccountBound",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isNullifierBound",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nullifierToAccount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifyAndBind",
    values: [
      AddressLike,
      [BigNumberish, BigNumberish],
      [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      [BigNumberish, BigNumberish],
      BigNumberish[],
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "accountToNullifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "attesterMessageHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "attesterRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "expectedScope",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAccountBound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isNullifierBound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nullifierToAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyAndBind",
    data: BytesLike
  ): Result;
}

export namespace NullifierBoundEvent {
  export type InputTuple = [
    account: AddressLike,
    nullifier: BigNumberish,
    attestationId: BigNumberish,
    scope: BigNumberish
  ];
  export type OutputTuple = [
    account: string,
    nullifier: bigint,
    attestationId: bigint,
    scope: bigint
  ];
  export interface OutputObject {
    account: string;
    nullifier: bigint;
    attestationId: bigint;
    scope: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NullifierRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): NullifierRegistry;
  waitForDeployment(): Promise<this>;

  interface: NullifierRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  accountToNullifier: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  attesterMessageHash: TypedContractMethod<
    [account: AddressLike, pubSignals: BigNumberish[]],
    [string],
    "view"
  >;

  attesterRegistry: TypedContractMethod<[], [string], "view">;

  expectedScope: TypedContractMethod<[], [bigint], "view">;

  isAccountBound: TypedContractMethod<
    [account: AddressLike],
    [boolean],
    "view"
  >;

  isNullifierBound: TypedContractMethod<
    [nullifier: BigNumberish],
    [boolean],
    "view"
  >;

  nullifierToAccount: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  verifier: TypedContractMethod<[], [string], "view">;

  verifyAndBind: TypedContractMethod<
    [
      account: AddressLike,
      a: [BigNumberish, BigNumberish],
      b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      c: [BigNumberish, BigNumberish],
      pubSignals: BigNumberish[],
      attesterSig: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "accountToNullifier"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "attesterMessageHash"
  ): TypedContractMethod<
    [account: AddressLike, pubSignals: BigNumberish[]],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "attesterRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "expectedScope"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isAccountBound"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isNullifierBound"
  ): TypedContractMethod<[nullifier: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "nullifierToAccount"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyAndBind"
  ): TypedContractMethod<
    [
      account: AddressLike,
      a: [BigNumberish, BigNumberish],
      b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      c: [BigNumberish, BigNumberish],
      pubSignals: BigNumberish[],
      attesterSig: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "NullifierBound"
  ): TypedContractEvent<
    NullifierBoundEvent.InputTuple,
    NullifierBoundEvent.OutputTuple,
    NullifierBoundEvent.OutputObject
  >;

  filters: {
    "NullifierBound(address,uint256,uint256,uint256)": TypedContractEvent<
      NullifierBoundEvent.InputTuple,
      NullifierBoundEvent.OutputTuple,
      NullifierBoundEvent.OutputObject
    >;
    NullifierBound: TypedContractEvent<
      NullifierBoundEvent.InputTuple,
      NullifierBoundEvent.OutputTuple,
      NullifierBoundEvent.OutputObject
    >;
  };
}
