/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface SelfAttesterRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptOwnership"
      | "addAttester"
      | "addAttesters"
      | "isTrustedAttester"
      | "owner"
      | "pendingOwner"
      | "removeAttester"
      | "renounceOwnership"
      | "toEthSignedMessageHash"
      | "transferOwnership"
      | "trustedAttesterCount"
      | "verifyAttesterSig"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AttesterAdded"
      | "AttesterRemoved"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addAttester",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addAttesters",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "isTrustedAttester",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeAttester",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "toEthSignedMessageHash",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trustedAttesterCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAttesterSig",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addAttester",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addAttesters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTrustedAttester",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAttester",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toEthSignedMessageHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustedAttesterCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAttesterSig",
    data: BytesLike
  ): Result;
}

export namespace AttesterAddedEvent {
  export type InputTuple = [attester: AddressLike];
  export type OutputTuple = [attester: string];
  export interface OutputObject {
    attester: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AttesterRemovedEvent {
  export type InputTuple = [attester: AddressLike];
  export type OutputTuple = [attester: string];
  export interface OutputObject {
    attester: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SelfAttesterRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): SelfAttesterRegistry;
  waitForDeployment(): Promise<this>;

  interface: SelfAttesterRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  addAttester: TypedContractMethod<
    [attester: AddressLike],
    [void],
    "nonpayable"
  >;

  addAttesters: TypedContractMethod<
    [attesters: AddressLike[]],
    [void],
    "nonpayable"
  >;

  isTrustedAttester: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  removeAttester: TypedContractMethod<
    [attester: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  toEthSignedMessageHash: TypedContractMethod<
    [hash: BytesLike],
    [string],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  trustedAttesterCount: TypedContractMethod<[], [bigint], "view">;

  verifyAttesterSig: TypedContractMethod<
    [messageHash: BytesLike, signature: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addAttester"
  ): TypedContractMethod<[attester: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addAttesters"
  ): TypedContractMethod<[attesters: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isTrustedAttester"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeAttester"
  ): TypedContractMethod<[attester: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "toEthSignedMessageHash"
  ): TypedContractMethod<[hash: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "trustedAttesterCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "verifyAttesterSig"
  ): TypedContractMethod<
    [messageHash: BytesLike, signature: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "AttesterAdded"
  ): TypedContractEvent<
    AttesterAddedEvent.InputTuple,
    AttesterAddedEvent.OutputTuple,
    AttesterAddedEvent.OutputObject
  >;
  getEvent(
    key: "AttesterRemoved"
  ): TypedContractEvent<
    AttesterRemovedEvent.InputTuple,
    AttesterRemovedEvent.OutputTuple,
    AttesterRemovedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AttesterAdded(address)": TypedContractEvent<
      AttesterAddedEvent.InputTuple,
      AttesterAddedEvent.OutputTuple,
      AttesterAddedEvent.OutputObject
    >;
    AttesterAdded: TypedContractEvent<
      AttesterAddedEvent.InputTuple,
      AttesterAddedEvent.OutputTuple,
      AttesterAddedEvent.OutputObject
    >;

    "AttesterRemoved(address)": TypedContractEvent<
      AttesterRemovedEvent.InputTuple,
      AttesterRemovedEvent.OutputTuple,
      AttesterRemovedEvent.OutputObject
    >;
    AttesterRemoved: TypedContractEvent<
      AttesterRemovedEvent.InputTuple,
      AttesterRemovedEvent.OutputTuple,
      AttesterRemovedEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
