/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface AuthorityManagerBaseInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_PASSKEYS"
      | "authorityCount"
      | "getAuthority"
      | "passkeyCount"
      | "upgradeLocked"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuthorityAdded"
      | "AuthorityRevoked"
      | "FirstPasskeyEnrolled"
      | "RatchetFired"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_PASSKEYS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "authorityCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAuthority",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "passkeyCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeLocked",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_PASSKEYS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorityCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "passkeyCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeLocked",
    data: BytesLike
  ): Result;
}

export namespace AuthorityAddedEvent {
  export type InputTuple = [
    authorityId: BigNumberish,
    module: AddressLike,
    tier: BigNumberish,
    kind: BytesLike
  ];
  export type OutputTuple = [
    authorityId: bigint,
    module: string,
    tier: bigint,
    kind: string
  ];
  export interface OutputObject {
    authorityId: bigint;
    module: string;
    tier: bigint;
    kind: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuthorityRevokedEvent {
  export type InputTuple = [authorityId: BigNumberish];
  export type OutputTuple = [authorityId: bigint];
  export interface OutputObject {
    authorityId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FirstPasskeyEnrolledEvent {
  export type InputTuple = [
    lowAuthorityId: BigNumberish,
    passkeyAuthorityId: BigNumberish
  ];
  export type OutputTuple = [
    lowAuthorityId: bigint,
    passkeyAuthorityId: bigint
  ];
  export interface OutputObject {
    lowAuthorityId: bigint;
    passkeyAuthorityId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RatchetFiredEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AuthorityManagerBase extends BaseContract {
  connect(runner?: ContractRunner | null): AuthorityManagerBase;
  waitForDeployment(): Promise<this>;

  interface: AuthorityManagerBaseInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_PASSKEYS: TypedContractMethod<[], [bigint], "view">;

  authorityCount: TypedContractMethod<[], [bigint], "view">;

  getAuthority: TypedContractMethod<
    [authorityId: BigNumberish],
    [
      [string, bigint, boolean, string] & {
        module: string;
        tier: bigint;
        active: boolean;
        config: string;
      }
    ],
    "view"
  >;

  passkeyCount: TypedContractMethod<[], [bigint], "view">;

  upgradeLocked: TypedContractMethod<[], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_PASSKEYS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "authorityCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAuthority"
  ): TypedContractMethod<
    [authorityId: BigNumberish],
    [
      [string, bigint, boolean, string] & {
        module: string;
        tier: bigint;
        active: boolean;
        config: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "passkeyCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "upgradeLocked"
  ): TypedContractMethod<[], [boolean], "view">;

  getEvent(
    key: "AuthorityAdded"
  ): TypedContractEvent<
    AuthorityAddedEvent.InputTuple,
    AuthorityAddedEvent.OutputTuple,
    AuthorityAddedEvent.OutputObject
  >;
  getEvent(
    key: "AuthorityRevoked"
  ): TypedContractEvent<
    AuthorityRevokedEvent.InputTuple,
    AuthorityRevokedEvent.OutputTuple,
    AuthorityRevokedEvent.OutputObject
  >;
  getEvent(
    key: "FirstPasskeyEnrolled"
  ): TypedContractEvent<
    FirstPasskeyEnrolledEvent.InputTuple,
    FirstPasskeyEnrolledEvent.OutputTuple,
    FirstPasskeyEnrolledEvent.OutputObject
  >;
  getEvent(
    key: "RatchetFired"
  ): TypedContractEvent<
    RatchetFiredEvent.InputTuple,
    RatchetFiredEvent.OutputTuple,
    RatchetFiredEvent.OutputObject
  >;

  filters: {
    "AuthorityAdded(uint256,address,uint8,bytes32)": TypedContractEvent<
      AuthorityAddedEvent.InputTuple,
      AuthorityAddedEvent.OutputTuple,
      AuthorityAddedEvent.OutputObject
    >;
    AuthorityAdded: TypedContractEvent<
      AuthorityAddedEvent.InputTuple,
      AuthorityAddedEvent.OutputTuple,
      AuthorityAddedEvent.OutputObject
    >;

    "AuthorityRevoked(uint256)": TypedContractEvent<
      AuthorityRevokedEvent.InputTuple,
      AuthorityRevokedEvent.OutputTuple,
      AuthorityRevokedEvent.OutputObject
    >;
    AuthorityRevoked: TypedContractEvent<
      AuthorityRevokedEvent.InputTuple,
      AuthorityRevokedEvent.OutputTuple,
      AuthorityRevokedEvent.OutputObject
    >;

    "FirstPasskeyEnrolled(uint256,uint256)": TypedContractEvent<
      FirstPasskeyEnrolledEvent.InputTuple,
      FirstPasskeyEnrolledEvent.OutputTuple,
      FirstPasskeyEnrolledEvent.OutputObject
    >;
    FirstPasskeyEnrolled: TypedContractEvent<
      FirstPasskeyEnrolledEvent.InputTuple,
      FirstPasskeyEnrolledEvent.OutputTuple,
      FirstPasskeyEnrolledEvent.OutputObject
    >;

    "RatchetFired()": TypedContractEvent<
      RatchetFiredEvent.InputTuple,
      RatchetFiredEvent.OutputTuple,
      RatchetFiredEvent.OutputObject
    >;
    RatchetFired: TypedContractEvent<
      RatchetFiredEvent.InputTuple,
      RatchetFiredEvent.OutputTuple,
      RatchetFiredEvent.OutputObject
    >;
  };
}
