/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IEntryPoint {
  export type PackedUserOperationStruct = {
    sender: AddressLike;
    nonce: BigNumberish;
    initCode: BytesLike;
    callData: BytesLike;
    accountGasLimits: BytesLike;
    preVerificationGas: BigNumberish;
    gasFees: BytesLike;
    paymasterAndData: BytesLike;
    signature: BytesLike;
  };

  export type PackedUserOperationStructOutput = [
    sender: string,
    nonce: bigint,
    initCode: string,
    callData: string,
    accountGasLimits: string,
    preVerificationGas: bigint,
    gasFees: string,
    paymasterAndData: string,
    signature: string
  ] & {
    sender: string;
    nonce: bigint;
    initCode: string;
    callData: string;
    accountGasLimits: string;
    preVerificationGas: bigint;
    gasFees: string;
    paymasterAndData: string;
    signature: string;
  };
}

export interface CofferdamAccount4337Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "ENTRY_POINT"
      | "MAX_PASSKEYS"
      | "addAuthority"
      | "addOwnerAddress"
      | "addOwnerPublicKey"
      | "authorityCount"
      | "enrollFirstPasskey"
      | "execute"
      | "executeBatch"
      | "getAuthority"
      | "isValidSignature"
      | "passkeyCount"
      | "revokeAuthority"
      | "upgradeLocked"
      | "validateUserOp"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuthorityAdded"
      | "AuthorityRevoked"
      | "FirstPasskeyEnrolled"
      | "RatchetFired"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ENTRY_POINT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_PASSKEYS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addAuthority",
    values: [BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addOwnerAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addOwnerPublicKey",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorityCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "enrollFirstPasskey",
    values: [BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeBatch",
    values: [AddressLike[], BigNumberish[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuthority",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidSignature",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "passkeyCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAuthority",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeLocked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "validateUserOp",
    values: [IEntryPoint.PackedUserOperationStruct, BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "ENTRY_POINT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_PASSKEYS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addOwnerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addOwnerPublicKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorityCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enrollFirstPasskey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "passkeyCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeLocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateUserOp",
    data: BytesLike
  ): Result;
}

export namespace AuthorityAddedEvent {
  export type InputTuple = [
    authorityId: BigNumberish,
    module: AddressLike,
    tier: BigNumberish,
    kind: BytesLike
  ];
  export type OutputTuple = [
    authorityId: bigint,
    module: string,
    tier: bigint,
    kind: string
  ];
  export interface OutputObject {
    authorityId: bigint;
    module: string;
    tier: bigint;
    kind: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuthorityRevokedEvent {
  export type InputTuple = [authorityId: BigNumberish];
  export type OutputTuple = [authorityId: bigint];
  export interface OutputObject {
    authorityId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FirstPasskeyEnrolledEvent {
  export type InputTuple = [
    lowAuthorityId: BigNumberish,
    passkeyAuthorityId: BigNumberish
  ];
  export type OutputTuple = [
    lowAuthorityId: bigint,
    passkeyAuthorityId: bigint
  ];
  export interface OutputObject {
    lowAuthorityId: bigint;
    passkeyAuthorityId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RatchetFiredEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CofferdamAccount4337 extends BaseContract {
  connect(runner?: ContractRunner | null): CofferdamAccount4337;
  waitForDeployment(): Promise<this>;

  interface: CofferdamAccount4337Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ENTRY_POINT: TypedContractMethod<[], [string], "view">;

  MAX_PASSKEYS: TypedContractMethod<[], [bigint], "view">;

  addAuthority: TypedContractMethod<
    [authorityId: BigNumberish, newModule: AddressLike, newConfig: BytesLike],
    [void],
    "nonpayable"
  >;

  addOwnerAddress: TypedContractMethod<
    [owner: AddressLike],
    [void],
    "nonpayable"
  >;

  addOwnerPublicKey: TypedContractMethod<
    [qx: BytesLike, qy: BytesLike],
    [void],
    "nonpayable"
  >;

  authorityCount: TypedContractMethod<[], [bigint], "view">;

  enrollFirstPasskey: TypedContractMethod<
    [
      lowAuthorityId: BigNumberish,
      passkeyModule: AddressLike,
      passkeyConfig: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  execute: TypedContractMethod<
    [target: AddressLike, value: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;

  executeBatch: TypedContractMethod<
    [targets: AddressLike[], values: BigNumberish[], data: BytesLike[]],
    [void],
    "nonpayable"
  >;

  getAuthority: TypedContractMethod<
    [authorityId: BigNumberish],
    [
      [string, bigint, boolean, string] & {
        module: string;
        tier: bigint;
        active: boolean;
        config: string;
      }
    ],
    "view"
  >;

  isValidSignature: TypedContractMethod<
    [digest: BytesLike, sig: BytesLike],
    [string],
    "view"
  >;

  passkeyCount: TypedContractMethod<[], [bigint], "view">;

  revokeAuthority: TypedContractMethod<
    [authorityId: BigNumberish, targetId: BigNumberish],
    [void],
    "nonpayable"
  >;

  upgradeLocked: TypedContractMethod<[], [boolean], "view">;

  validateUserOp: TypedContractMethod<
    [
      userOp: IEntryPoint.PackedUserOperationStruct,
      userOpHash: BytesLike,
      missingAccountFunds: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ENTRY_POINT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_PASSKEYS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addAuthority"
  ): TypedContractMethod<
    [authorityId: BigNumberish, newModule: AddressLike, newConfig: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addOwnerAddress"
  ): TypedContractMethod<[owner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addOwnerPublicKey"
  ): TypedContractMethod<[qx: BytesLike, qy: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorityCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "enrollFirstPasskey"
  ): TypedContractMethod<
    [
      lowAuthorityId: BigNumberish,
      passkeyModule: AddressLike,
      passkeyConfig: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [target: AddressLike, value: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeBatch"
  ): TypedContractMethod<
    [targets: AddressLike[], values: BigNumberish[], data: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAuthority"
  ): TypedContractMethod<
    [authorityId: BigNumberish],
    [
      [string, bigint, boolean, string] & {
        module: string;
        tier: bigint;
        active: boolean;
        config: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isValidSignature"
  ): TypedContractMethod<[digest: BytesLike, sig: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "passkeyCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "revokeAuthority"
  ): TypedContractMethod<
    [authorityId: BigNumberish, targetId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeLocked"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "validateUserOp"
  ): TypedContractMethod<
    [
      userOp: IEntryPoint.PackedUserOperationStruct,
      userOpHash: BytesLike,
      missingAccountFunds: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  getEvent(
    key: "AuthorityAdded"
  ): TypedContractEvent<
    AuthorityAddedEvent.InputTuple,
    AuthorityAddedEvent.OutputTuple,
    AuthorityAddedEvent.OutputObject
  >;
  getEvent(
    key: "AuthorityRevoked"
  ): TypedContractEvent<
    AuthorityRevokedEvent.InputTuple,
    AuthorityRevokedEvent.OutputTuple,
    AuthorityRevokedEvent.OutputObject
  >;
  getEvent(
    key: "FirstPasskeyEnrolled"
  ): TypedContractEvent<
    FirstPasskeyEnrolledEvent.InputTuple,
    FirstPasskeyEnrolledEvent.OutputTuple,
    FirstPasskeyEnrolledEvent.OutputObject
  >;
  getEvent(
    key: "RatchetFired"
  ): TypedContractEvent<
    RatchetFiredEvent.InputTuple,
    RatchetFiredEvent.OutputTuple,
    RatchetFiredEvent.OutputObject
  >;

  filters: {
    "AuthorityAdded(uint256,address,uint8,bytes32)": TypedContractEvent<
      AuthorityAddedEvent.InputTuple,
      AuthorityAddedEvent.OutputTuple,
      AuthorityAddedEvent.OutputObject
    >;
    AuthorityAdded: TypedContractEvent<
      AuthorityAddedEvent.InputTuple,
      AuthorityAddedEvent.OutputTuple,
      AuthorityAddedEvent.OutputObject
    >;

    "AuthorityRevoked(uint256)": TypedContractEvent<
      AuthorityRevokedEvent.InputTuple,
      AuthorityRevokedEvent.OutputTuple,
      AuthorityRevokedEvent.OutputObject
    >;
    AuthorityRevoked: TypedContractEvent<
      AuthorityRevokedEvent.InputTuple,
      AuthorityRevokedEvent.OutputTuple,
      AuthorityRevokedEvent.OutputObject
    >;

    "FirstPasskeyEnrolled(uint256,uint256)": TypedContractEvent<
      FirstPasskeyEnrolledEvent.InputTuple,
      FirstPasskeyEnrolledEvent.OutputTuple,
      FirstPasskeyEnrolledEvent.OutputObject
    >;
    FirstPasskeyEnrolled: TypedContractEvent<
      FirstPasskeyEnrolledEvent.InputTuple,
      FirstPasskeyEnrolledEvent.OutputTuple,
      FirstPasskeyEnrolledEvent.OutputObject
    >;

    "RatchetFired()": TypedContractEvent<
      RatchetFiredEvent.InputTuple,
      RatchetFiredEvent.OutputTuple,
      RatchetFiredEvent.OutputObject
    >;
    RatchetFired: TypedContractEvent<
      RatchetFiredEvent.InputTuple,
      RatchetFiredEvent.OutputTuple,
      RatchetFiredEvent.OutputObject
    >;
  };
}
