/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface CofferdamAccountFactory4337Interface extends Interface {
  getFunction(
    nameOrSignature: "ENTRY_POINT" | "deployAccount" | "getAddress"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "AccountDeployed"): EventFragment;

  encodeFunctionData(
    functionFragment: "ENTRY_POINT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployAccount",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAddress",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "ENTRY_POINT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAddress", data: BytesLike): Result;
}

export namespace AccountDeployedEvent {
  export type InputTuple = [
    account: AddressLike,
    initialModule: AddressLike,
    salt: BytesLike
  ];
  export type OutputTuple = [
    account: string,
    initialModule: string,
    salt: string
  ];
  export interface OutputObject {
    account: string;
    initialModule: string;
    salt: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CofferdamAccountFactory4337 extends BaseContract {
  connect(runner?: ContractRunner | null): CofferdamAccountFactory4337;
  waitForDeployment(): Promise<this>;

  interface: CofferdamAccountFactory4337Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ENTRY_POINT: TypedContractMethod<[], [string], "view">;

  deployAccount: TypedContractMethod<
    [initialModule: AddressLike, initialConfig: BytesLike, salt: BytesLike],
    [string],
    "nonpayable"
  >;

  getAddress: TypedContractMethod<
    [initialModule: AddressLike, initialConfig: BytesLike, salt: BytesLike],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ENTRY_POINT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deployAccount"
  ): TypedContractMethod<
    [initialModule: AddressLike, initialConfig: BytesLike, salt: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAddress"
  ): TypedContractMethod<
    [initialModule: AddressLike, initialConfig: BytesLike, salt: BytesLike],
    [string],
    "view"
  >;

  getEvent(
    key: "AccountDeployed"
  ): TypedContractEvent<
    AccountDeployedEvent.InputTuple,
    AccountDeployedEvent.OutputTuple,
    AccountDeployedEvent.OutputObject
  >;

  filters: {
    "AccountDeployed(address,address,bytes32)": TypedContractEvent<
      AccountDeployedEvent.InputTuple,
      AccountDeployedEvent.OutputTuple,
      AccountDeployedEvent.OutputObject
    >;
    AccountDeployed: TypedContractEvent<
      AccountDeployedEvent.InputTuple,
      AccountDeployedEvent.OutputTuple,
      AccountDeployedEvent.OutputObject
    >;
  };
}
