/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IB20Factory,
  IB20FactoryInterface,
} from "../../../../contracts/interfaces/IB20Factory.sol/IB20Factory";

const _abi = [
  {
    inputs: [
      {
        internalType: "enum IB20Factory.Variant",
        name: "variant",
        type: "uint8",
      },
      {
        internalType: "bytes32",
        name: "salt",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "params",
        type: "bytes",
      },
      {
        internalType: "bytes[]",
        name: "initCalls",
        type: "bytes[]",
      },
    ],
    name: "createB20",
    outputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum IB20Factory.Variant",
        name: "variant",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "deployer",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "salt",
        type: "bytes32",
      },
    ],
    name: "getB20Address",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "addr",
        type: "address",
      },
    ],
    name: "isB20",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "addr",
        type: "address",
      },
    ],
    name: "isB20Initialized",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IB20Factory__factory {
  static readonly abi = _abi;
  static createInterface(): IB20FactoryInterface {
    return new Interface(_abi) as IB20FactoryInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IB20Factory {
    return new Contract(address, _abi, runner) as unknown as IB20Factory;
  }
}
