/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IB20Factory__factory } from "./IB20Factory__factory";
export { IB20Token__factory } from "./IB20Token__factory";
export { IPolicyRegistry__factory } from "./IPolicyRegistry__factory";
