/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPolicyRegistry,
  IPolicyRegistryInterface,
} from "../../../../contracts/interfaces/IB20Factory.sol/IPolicyRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "admin",
        type: "address",
      },
      {
        internalType: "enum IPolicyRegistry.PolicyType",
        name: "policyType",
        type: "uint8",
      },
    ],
    name: "createPolicy",
    outputs: [
      {
        internalType: "uint64",
        name: "policyId",
        type: "uint64",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "admin",
        type: "address",
      },
      {
        internalType: "enum IPolicyRegistry.PolicyType",
        name: "policyType",
        type: "uint8",
      },
      {
        internalType: "address[]",
        name: "accounts",
        type: "address[]",
      },
    ],
    name: "createPolicyWithAccounts",
    outputs: [
      {
        internalType: "uint64",
        name: "policyId",
        type: "uint64",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "policyId",
        type: "uint64",
      },
    ],
    name: "finalizeUpdateAdmin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "policyId",
        type: "uint64",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "isAuthorized",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "policyId",
        type: "uint64",
      },
    ],
    name: "policyAdmin",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "policyId",
        type: "uint64",
      },
    ],
    name: "policyExists",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "policyId",
        type: "uint64",
      },
    ],
    name: "renounceAdmin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "policyId",
        type: "uint64",
      },
      {
        internalType: "address",
        name: "newAdmin",
        type: "address",
      },
    ],
    name: "stageUpdateAdmin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "policyId",
        type: "uint64",
      },
      {
        internalType: "bool",
        name: "allow",
        type: "bool",
      },
      {
        internalType: "address[]",
        name: "accounts",
        type: "address[]",
      },
    ],
    name: "updateAllowlist",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "policyId",
        type: "uint64",
      },
      {
        internalType: "bool",
        name: "block",
        type: "bool",
      },
      {
        internalType: "address[]",
        name: "accounts",
        type: "address[]",
      },
    ],
    name: "updateBlocklist",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPolicyRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IPolicyRegistryInterface {
    return new Interface(_abi) as IPolicyRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPolicyRegistry {
    return new Contract(address, _abi, runner) as unknown as IPolicyRegistry;
  }
}
