/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface CofferdamWalletBindInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bindWallet"
      | "bindings"
      | "isBound"
      | "ssoProofs"
      | "unbindWallet"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "WalletBound" | "WalletUnbound"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "bindWallet",
    values: [BytesLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "bindings",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isBound",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ssoProofs",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unbindWallet",
    values: [BytesLike, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "bindWallet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bindings", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isBound", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ssoProofs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unbindWallet",
    data: BytesLike
  ): Result;
}

export namespace WalletBoundEvent {
  export type InputTuple = [
    companyAnchor: BytesLike,
    workerWallet: AddressLike,
    ssoProofHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    companyAnchor: string,
    workerWallet: string,
    ssoProofHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    companyAnchor: string;
    workerWallet: string;
    ssoProofHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WalletUnboundEvent {
  export type InputTuple = [
    companyAnchor: BytesLike,
    workerWallet: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    companyAnchor: string,
    workerWallet: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    companyAnchor: string;
    workerWallet: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CofferdamWalletBind extends BaseContract {
  connect(runner?: ContractRunner | null): CofferdamWalletBind;
  waitForDeployment(): Promise<this>;

  interface: CofferdamWalletBindInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bindWallet: TypedContractMethod<
    [
      _companyAnchor: BytesLike,
      _workerWallet: AddressLike,
      _ssoProofHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  bindings: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isBound: TypedContractMethod<
    [_companyAnchor: BytesLike, _workerWallet: AddressLike],
    [boolean],
    "view"
  >;

  ssoProofs: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [string],
    "view"
  >;

  unbindWallet: TypedContractMethod<
    [_companyAnchor: BytesLike, _workerWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bindWallet"
  ): TypedContractMethod<
    [
      _companyAnchor: BytesLike,
      _workerWallet: AddressLike,
      _ssoProofHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "bindings"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isBound"
  ): TypedContractMethod<
    [_companyAnchor: BytesLike, _workerWallet: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "ssoProofs"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "unbindWallet"
  ): TypedContractMethod<
    [_companyAnchor: BytesLike, _workerWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "WalletBound"
  ): TypedContractEvent<
    WalletBoundEvent.InputTuple,
    WalletBoundEvent.OutputTuple,
    WalletBoundEvent.OutputObject
  >;
  getEvent(
    key: "WalletUnbound"
  ): TypedContractEvent<
    WalletUnboundEvent.InputTuple,
    WalletUnboundEvent.OutputTuple,
    WalletUnboundEvent.OutputObject
  >;

  filters: {
    "WalletBound(bytes32,address,bytes32,uint48)": TypedContractEvent<
      WalletBoundEvent.InputTuple,
      WalletBoundEvent.OutputTuple,
      WalletBoundEvent.OutputObject
    >;
    WalletBound: TypedContractEvent<
      WalletBoundEvent.InputTuple,
      WalletBoundEvent.OutputTuple,
      WalletBoundEvent.OutputObject
    >;

    "WalletUnbound(bytes32,address,uint48)": TypedContractEvent<
      WalletUnboundEvent.InputTuple,
      WalletUnboundEvent.OutputTuple,
      WalletUnboundEvent.OutputObject
    >;
    WalletUnbound: TypedContractEvent<
      WalletUnboundEvent.InputTuple,
      WalletUnboundEvent.OutputTuple,
      WalletUnboundEvent.OutputObject
    >;
  };
}
