/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  RejectingGroth16Verifier,
  RejectingGroth16VerifierInterface,
} from "../../../../contracts/test/MockGroth16Verifier.sol/RejectingGroth16Verifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[2]",
        name: "",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[2][2]",
        name: "",
        type: "uint256[2][2]",
      },
      {
        internalType: "uint256[2]",
        name: "",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[21]",
        name: "",
        type: "uint256[21]",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608080604052346013576093908160188239f35b5f80fdfe60808060405260043610156011575f80fd5b5f3560e01c635debc07e146023575f80fd5b346059576103a0366003190112605957366044116059573660c4116059573661010411605957366103a411605957805f60209252f35b5f80fdfea2646970667358221220f717627e3664832de9c5800d9f7714b8bfaf35050441e39d04c9975d50b6405e64736f6c634300081c0033";

type RejectingGroth16VerifierConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: RejectingGroth16VerifierConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class RejectingGroth16Verifier__factory extends ContractFactory {
  constructor(...args: RejectingGroth16VerifierConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      RejectingGroth16Verifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): RejectingGroth16Verifier__factory {
    return super.connect(runner) as RejectingGroth16Verifier__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): RejectingGroth16VerifierInterface {
    return new Interface(_abi) as RejectingGroth16VerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): RejectingGroth16Verifier {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as RejectingGroth16Verifier;
  }
}
